cryostatio/cryostat-operator

- Makefile
- bundle/container-jfr-operator.v0.0.3.clusterserviceversion.yaml
- pkg/controller/containerjfr/containerjfr_controller.go
> Correct Grafana environment variables with URL protocol

- .osdk-scorecard.yaml
- bundle/container-jfr-operator.v0.0.6.clusterserviceversion.yaml
https://github.com/operator-framework/community-operators/blob/master/docs/required-fields.md
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md
https://operatorhub.io/preview
Some values are still placeholders or should be generated, but this at
least fills in some of the blanks currently presented in the OperatorHub
installation UI
> [WIP] Fill in ClusterServiceVersion metadata

- pkg/client/containerjfr_client.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
> Websocket subprotocol token

- .osdk-scorecard.yaml
- Makefile
- bundle/container-jfr-operator-bundle.package.yaml
- bundle/container-jfr-operator.v0.3.0.clusterserviceversion.yaml
This updates our Makefile, CSV and related files to use the newest image tag from quay.io.
Fixes #57
> Update operator version to 0.3.0

- README.md
> Add documentation about Marketplace and minimal deployments

- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
Related to rh-jmc-team/container-jfr#124
> Explicitly set OpenShift platform

- pkg/controller/flightrecorder/flightrecorder_controller.go
This PR changes the `FlightRecorder` controller to query the name of the `ContainerJFR` custom resource in the same namespace. It then uses this name in order to find the service used to connect to Container JFR, instead of the current hardcoded "containerjfr" name.
If there's more than one `ContainerJFR` in the namespace, we log a message and just take the first one in the list. I can't think of any practical reason for there to be more than one.
Fixes: https://github.com/rh-jmc-team/container-jfr-operator/issues/67
> Get ContainerJFR name from CR

- API.md
This PR updates the API usage documentation to reflect changes introduced by https://github.com/rh-jmc-team/container-jfr-operator/pull/72.
Fixes https://github.com/rh-jmc-team/container-jfr-operator/issues/78
> Update API doc with changes from API revision

- pkg/controller/recording/recording_controller.go
With the connectionless changes in Container JFR, non-archived download URLs now work without requiring an existing JMX connection. This PR adds the download URL for in-memory recordings, as returned by the "list" command. If/when the recording is archived, the URL is replaced with a link to the archived recording.
This changed the logic a bit in determining when to call the "save" command. Before, if the download URL was absent from the Recording CR and the recording was stopped, we knew to call "save" then. Now, once the recording is stopped, we check if the current download URL is an archived one, and if not we call "save" and update the URL.
> List non-archived download URLs in Recording CR

- pkg/controller/containerjfr/containerjfr_controller.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
> Store RJMX credentials in Secret

- pkg/controller/containerjfr/containerjfr_controller.go
> Watch own deployment

- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
> Specify CONTAINER_JFR_TEMPLATE_PATH env var

- pkg/controller/containerjfr/certmanager.go
- pkg/controller/containerjfr/containerjfr_controller.go
- pkg/controller/containerjfr/containerjfr_controller_test.go
- pkg/controller/containerjfr/containerjfr_suite_test.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
- test/reconciler.go
- test/resources.go
> Add unit tests for Containerjfr controller

- pkg/controller/endpoints/endpoints_controller.go
- pkg/controller/endpoints/endpoints_controller_test.go
- pkg/controller/endpoints/endpoints_suite_test.go
- test/reconciler.go
- test/resources.go
The one main part its not covering is if the Service corresponding to the Endpoints is owned by ContainerJFR, I am a bit confused as to how the service gets created in the first place.  Fixes #136
> Add endpoint tests

- Makefile
- README.md
> Makefile and README updates for sdk 1.0

- controllers/common/resource_definitions/resource_definitions.go
> Update container-jfr to BETA6

- .mergify.yml
This file has the same configuration as in Cryostat.
Relates to: #214
> ci(mergify): add mergify config for backports

- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/default/image_tag_patch.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/common/resource_definitions/imagetag_generated.go
Fixes #248 
Depends on https://github.com/cryostatio/cryostat/issues/672
> chore(version): update project version 2.1.0-dev

- Makefile
- README.md
> fix(cert-manager): Upgrade cert-manager to v1.5.3

- README.md
Intended to mimic other README's for Cryostat subprojects.
> docs(readme): add see also section to README

- Makefile
> fix(makefile): Deploy bundle with BUNDLE_IMG

- api/v1beta1/cryostat_types.go
> feat(printer-column): Printer Column for Application URL

- bundle.Dockerfile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- bundle/metadata/annotations.yaml
Regenerated bundle after adding `additionalPrinterColumns` metadata in #333. 
Related to: #309
> fix(printer-column): add printer column to CSV

- README.md
Related https://github.com/cryostatio/cryostat/issues/717
Depends on https://github.com/cryostatio/cryostat/pull/786
> docs(authentication): Update web-client login info

- api/v1beta1/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- docs/config.md
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
> fix(WebSocket): Update ws limit

- README.md
- api/v1beta1/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
> docs(crd): minimal mode includes web client

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
This is a fix to mount any user-supplied certs in `spec.trustedCertSecrets` even if cert-manager is disabled.
You can test this out with the following sample app (with the attached certificate):
```
kubectl run vertx-fib-demo --image=quay.io/andrewazores/vertx-fib-demo:0.7.0 --env=USE_SSL=true
kubectl expose pod vertx-fib-demo --port 9093
kubectl patch svc vertx-fib-demo -p '{"spec": {"ports": [{"port": 9093, "name": "jfr-jmx"}]}}'
kubectl create secret generic vertx-fib-demo-tls --from-file=tls.crt=vertx-fib-demo.txt
```
There are 3 cases you can verify:
1. Cryostat still deploys with cert-manager disabled and no trusted certs, but you cannot connect to the sample app because it is untrusted.
```yaml
apiVersion: v1
items:
- apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat …
```
> fix(cert-secrets): mount user certs when cert-manager disabled

- docs/config.md
> docs(config): add resource requirements to config guide

- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/default/image_tag_patch.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/common/resource_definitions/imagetag_generated.go
Fixes: https://github.com/cryostatio/cryostat/issues/997
Depends on: https://github.com/cryostatio/cryostat/pull/998
> build(version): set versions for 2.1.1 release

- internal/controllers/cryostat_controller_test.go
- internal/controllers/routes.go
- internal/test/resources.go
Fixes #407 
Users can now define labels for routes in Cryostat CR.
> feat(labels): allow users to define labels/annotations for routes

- Makefile
> test(sample): update sample apps

- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- config/scorecard/patches/custom.config.yaml
Related to: https://github.com/cryostatio/cryostat/issues/1118
> build(version): bump versions for 2.3.0-dev

- go.mod
- go.sum
> build(deps): replace go-restful with newer version

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
> fix(env): rename reports sidecar env var

- .mergify.yml
- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- config/scorecard/patches/custom.config.yaml
Related to https://github.com/cryostatio/cryostat/issues/1459
> build(config): update makefile and mergify for 2.3 release

- Makefile
- config/samples/sample-app-agent.yml
> feat(sample): add quarkus-test-agent sample app

- .github/workflows/ci.yaml
- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
Related to https://github.com/cryostatio/cryostat/issues/1329
Test run on my fork: https://github.com/andrewazores/cryostat-operator/actions/runs/5871523648/job/15921065157
The `scorecard-test` job failed because I didn't define the GitHub Packages secret so it wasn't able to push to `ghcr.io`.
https://quay.io/repository/andrewazores/cryostat-operator?tab=tags
> ci(multiarch): build multiarch OCI manifest images

- internal/controllers/ingresses.go
- internal/controllers/reconciler_test.go
- internal/controllers/routes.go
- internal/controllers/services.go
- internal/test/resources.go
> fix(network): app & component labels for network objects

- Makefile
See #636
Fixes #634 
I used the git reflog and attempted to cherry-pick the correct changes back together after failing to properly rebase @pektezol 's previous PR. This PR is a backup in case the original one cannot be fully recovered.
> chore(build): add short summaries to targets

- .github/workflows/test-ci-command.yml
> fix(CI): add comment when /build_test is finished

- Makefile
> feat(scorecard): add ability to select scorecard tests

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- hack/custom.config.yaml.in
- internal/images/custom-scorecard-tests/main.go
- internal/test/scorecard/clients.go
- internal/test/scorecard/common_utils.go
- internal/test/scorecard/tests.go
> test(scorecard): scorecard test for report generator 

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- internal/images/custom-scorecard-tests/main.go
- internal/test/scorecard/common_utils.go
- internal/test/scorecard/logger.go
- internal/test/scorecard/openshift.go
- internal/test/scorecard/tests.go
test(scorecard): use methods for more easily passing data
Fixes: #749 
Accidentally got rid of Elliott's PR when rebasing in #779
> test(scorecard): fix rebasing skipped commit

- .github/workflows/build-ci.yml
- .github/workflows/test-ci-push.yml
Fixes: #785
Adds `cryostat3` to list of branches that the push CI workflows run for.
We want development builds and tests run on them.
> ci(branch): run push workflows on cryostat3 branch

- api/v1beta1/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- bundle/tests/scorecard/config.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- config/scorecard/patches/custom.config.yaml
- hack/custom.config.yaml.in
- internal/images/custom-scorecard-tests/main.go
- internal/images/custom-scorecard-tests/rbac/scorecard_role.yaml
- internal/test/scorecard/clients.go
- internal/test/scorecard/common_utils.go
- internal/test/scorecard/logger.go
- internal/test/scorecard/tests.go
Fixes: #539 
- adds multi-namespace scorecard test for Cryostat 3.0
- amends all the scorecard tests to use operatorv1beta2 resources instead of operatorv1beta1
- removes mention of clustercryostats in bundle & config files
> test(scorecard): multi-namespace scorecard test for 3.0

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- internal/test/scorecard/common_utils.go
- internal/test/scorecard/tests.go
> test(scorecard): retry on cryostat update conflict

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/default/image_tag_patch.yaml
- config/manager/kustomization.yaml
- hack/image_tag_patch.yaml.in
Fixes: #811 
* Adds related image environment variables for the storage and database images
* Meets OLM criteria and allows substitution for images downstream
> fix(csv): add related images for storage and db

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/reconciler_test.go
- internal/controllers/secrets.go
- internal/test/resources.go
> chore(storage): rename storage secret

- .github/workflows/test-ci-reusable.yml
> chore(CI): update OLM to 0.28.0

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/reconciler.go
> chore(resources): cleanup v1beta1 resources

- Makefile
- README.md
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
Fixes: #842 
- Modify bundled CSV to put `v1beta2` crd first. These changes should be removed once OCP console team resolves https://issues.redhat.com/browse/OCPBUGS-34901
See #842
> chore(csv): put v1beta2 crd version first in owned list

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/default/image_tag_patch.yaml
- config/manager/kustomization.yaml
- internal/controllers/const_generated.go
> fix(versions): regenerate for new dev version

- internal/controllers/reconciler_test.go
> test(img): correct test to assert pull policy on db and storage containers

- .github/workflows/build-ci.yml
- .github/workflows/test-ci-reusable.yml
See https://github.com/cryostatio/cryostat-operator/pull/997#issuecomment-2575837478
2. *...*
> ci(criu): add CRIU PPA for Podman dependency

- Dockerfile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- internal/images/custom-scorecard-tests/Dockerfile
Related to https://github.com/cryostatio/cryostat/issues/650
2. *...*
> chore(base): upgrade to UBI9

- config/openshift/console-plugin/deployment-cryostat-plugin.yaml
See https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/111
See https://github.com/cryostatio/cryostat-openshift-console-plugin/pull/105
2. *...*
> chore(plugin): set default requests/limits and replicas

- internal/controllers/constants/constants.go
- internal/webhooks/agent/pod_defaulter.go
- internal/webhooks/agent/pod_defaulter_test.go
- internal/webhooks/agent/test/resources.go
> feat(agent): add labels for Harvester exit uploads

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
Fixes: https://github.com/cryostatio/cryostat-operator/issues/1059
> chore(scorecard): bump Scorecard tag

- internal/controllers/constants/constants.go
- internal/webhooks/agent/pod_defaulter.go
- internal/webhooks/agent/pod_defaulter_test.go
- internal/webhooks/agent/test/resources.go
> feat(agent): add default log level and control label

- Makefile
- config/scorecard/patches/custom.config.yaml
- internal/images/custom-scorecard-tests/main.go
- **chore(scorecard): add '-list' flag and implement wildcard test selection**
- **refactor, mapping of test names to functions happens in one place only**
- **allow scorecard to handle multiple test names**
> chore(scorecard): add '-list' flag and implement wildcard test selection

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
See cryostatio/cryostat-helm#255
Obsoletes #1137
2. *...*
> fix(cryostat): use container-internal curl cmd liveness probe
