- deploy/exposecontroller.yaml
The image repository used in the initial commit series was out of date, so this one-liner corrects it.
> Update exposecontroller image stream repo

- Makefile
I forgot to update the paths for the CRD/CR files in the Makefile's deploy target when we did the upgrade to Operator SDK 0.11.
> Fix CRD paths for deploy target

- Makefile
- bundle/container-jfr-operator-bundle.package.yaml
- bundle/container-jfr-operator.v0.0.7.clusterserviceversion.yaml
- bundle/container-jfr-operator.v0.0.8.clusterserviceversion.yaml
- deploy/crds/rhjmc.redhat.com_containerjfrs_crd.yaml
- deploy/crds/rhjmc.redhat.com_v1alpha1_containerjfr_cr.yaml
- pkg/apis/rhjmc/v1alpha1/containerjfr_types.go
- pkg/apis/rhjmc/v1alpha1/zz_generated.openapi.go
- pkg/controller/containerjfr/containerjfr_controller.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
If "Minimal" is set to true then container-jfr will be deployed with the
-minimal image variant, containing no web-client UI resources, and the
pod deployment will also not contain Grafana or jfr-datasource containers, services, or routes.
The Operator also creates/cleans up the additional services and routes if the Spec.Minimal field changes on an existing ContainerJFR. The Pod will be destroyed and recreated to match - it should be checked in the future that this can't be done more efficiently and less disruptively by updating the set of containers running within the Pod.
Fixes #27
> Add "Minimal" field to ContainerJFR spec

- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
The containerjfr environment variable "USE_LOW_MEMORY_PRESSURE_STREAMING" is intended to reduce the webserver memory footprint while streaming recordings out of the target JVM to the consumer (ex. user's web browser). It seems natural that the minimal deployment, aimed at reducing the overall application footprint as much as possible, should enable this option.
> Minimal deployment enables low-memory-pressure streaming

- go.sum
- pkg/controller/add_grafana.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
- pkg/controller/grafana/dashboard.go
- pkg/controller/grafana/grafana_controller.go
This PR aims to automate the Grafana setup, so that the jfr-datasource is already linked to Grafana as a SimpleJSON datasource and so that a pre-configured Grafana dashboard is provided for the user, so that no additional work is required on the user's part to gain some insight into a recording after clicking "View In Grafana" from the web client.
See #33 & #34
> Automatic Grafana setup

- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
Fixes #40
Readiness probes aren't added since none of the containers do anything particularly heavy at initialization time, so liveness is equivalent to readiness.
> Add liveness probes to all container definitions

- Makefile
- pkg/controller/containerjfr/containerjfr_controller.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
See #25
With this PR, the container-jfr Pod is placed into a Deployment, which allows it to be visible on the Topology view for developer accounts. Labels/annotations are also added to this Pod, which provide the arrow linking the container-jfr instance back up to its Operator parent. I spent some time trying to get the application grouping working, but this requires a corresponding label to be present on the Operator Deployment, which it does not seem is currently possible (https://godoc.org/github.com/operator-framework/operator-lifecycle-manager/pkg/controller/install contains no information about attaching labels or other metadata to the Deployment itself, only to its owned Pods). I did some manual testing and everything seems to still deploy and run correctly, both with the Makefile …
> Topology view

- Makefile
- README.md
~~This is based on top of the currently open Auth PR #45 . Only the last commit is new for this branch.~~
This simply adds the image-builder arg to the operator-sdk invocation, with `podman` specified as the image builder rather than the default Docker. This is motivated by `podman` requiring less setup, being rootless/daemonless, and along that same line, with Docker being incompatible with cgroupsv2 and therefore not currently working by default in Fedora 31. Since I'm using Fedora 31 this is a convenience win for me, but it also seems like a net benefit in general.
> Podman image builder

- Makefile
- deploy/crds/rhjmc.redhat.com_flightrecorders_crd.yaml
- pkg/apis/rhjmc/v1alpha1/flightrecorder_types.go
- pkg/apis/rhjmc/v1alpha1/zz_generated.openapi.go
- pkg/client/containerjfr_client.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
- pkg/controller/flightrecorder/flightrecorder_controller.go
- pkg/controller/service/service_controller.go
This is based on top of the currently open ~~Auth #45 and~~ podman builder #46 PRs.
The last ~~two~~ three commits in this branch replace the hardcoded exporter port number 8181 and JMX port number 9091 with named ports.
For the JMX target port of 9091, this is now used as a fallback rather than a hardcoded default. The service_controller still watches for new services to appear and for each new service it checks all of the defined service ports. If a port named "jmx" is found then the service is marked as a compatible target. If no "jmx" port is found but the 9091 port is found then it is also marked as compatible. If neither are found then the service is ignored as a potential target. Then, after the service_controller creates the FlightRecorder resource including this port number, the …
> Target jmx named port

- pkg/controller/containerjfr/containerjfr_controller.go
I noticed errors of the form `{"level":"error","ts":1579803672.526808,"logger":"controller_containerjfr","msg":"Failed to get newly created route"...` appearing in the log after creating new routes. I suspect this has something to do with the controller's client reading from a cache [1]. Fortunately, it looks like this Get call after Create is unnecessary. The Create call has a side-effect of updating the provided runtime object with a full copy provided by the API server.
Before Create call:
```json
{
"metadata": {
"name": "containerjfr-command",
"namespace": "default",
"creationTimestamp": null,
"ownerReferences": [
{
"apiVersion": "rhjmc.redhat.com/v1alpha1",
"kind": "ContainerJFR",
"name": "containerjfr",
"uid": "3184c6b5-3e2a-11ea-a9c4-52fdfc072182",
"controller": true, …
```
> Remove unnecessary Get call after creating route

- API.md
This PR adds a new documentation file with a brief introduction to the FlightRecorder API provided by our operator, along with instructions on how to use it to list, create and download recordings.
> Add documentation on how to use the API

- deploy/dev_operator.yaml
- pkg/client/command_types.go
- pkg/client/containerjfr_client.go
This PR takes advantage of the ID field added to command messages with https://github.com/rh-jmc-team/container-jfr/pull/117. We generate a UUID upon creating a CommandMessage using apimachinery's UUID util package.
When reading a response, we set this expected ID in the response struct that our decoder will attempt to unmarshal into. This allows our custom JSON decoder to verify the read ID is what we're expected before attempting to unmarshal the rest of the response. This prevents us from unmarshalling an unexpected payload type.
If the ID in the response is not what we're expecting, we return a special error indicating that the message was meant for another client. Our client will read in a loop until we receive the correct response, or some other error occurs. This seems to work …
> Use a UUID when communicating with command server

- README.md
- pkg/controller/containerjfr/containerjfr_controller.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
- pkg/controller/grafana/grafana_controller.go
See #50 and #51 . This PR results in Grafana being configured to use a generated
password rather than the insecure default credentials for its normal HTTP Basic
auth scheme. The generated password is stored in a Secret, with the contents
written into the Grafana container's environment variables. These generated
credentials are also retrieved and used by the Operator itself when it performs
its startup configuration of the Grafana instance (creating the datasource
and dashboard).
> Use generated Grafana credentials, not default

- pkg/client/containerjfr_client.go
- pkg/controller/recording/recording_controller.go
This PR modifies the Recordings controller to attempt to clean up recording resources in Container JFR when a `Recording` object is deleted by the user. The reconciler does this by adding a finalizer to each `Recording` object it sees. This finalizer prevents the object from being actually deleted until the reconciler removes the finalizer.
Once the reconciler detects the object is to be deleted, it attempts to send `delete` and `delete-saved` commands to Container JFR, to reclaim PVC space and resources within the JVM's pod. The logic is somewhat complex in order to handle a variety of corner cases. Here's how it works:
1. Delete saved recordings before trying to connect to a JVM via JMX. This allows `delete-saved` to succeed even if the JVM no longer exists.
2. If the `Recording` …
> Use finalizer to clean up deleted recordings

- deploy/crds/rhjmc.redhat.com_v1alpha2_recording_cr.yaml
- pkg/client/command_types.go
- pkg/client/containerjfr_client.go
- pkg/controller/common/common_reconciler.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
Also update controllers for updated connectionless API, currently
emulating a connection-oriented interface by holding internal state.
Finally, also replaces "ALL" event string with "template=ALL".
> Update container-jfr image version

- .osdk-scorecard.yaml
- Makefile
- deploy/olm-catalog/catalog-source.yaml
- deploy/olm-catalog/container-jfr-operator-bundle/0.5.0/container-jfr-operator-bundle.v0.5.0.clusterserviceversion.yaml
- deploy/olm-catalog/container-jfr-operator-bundle/0.5.0/rhjmc.redhat.com_containerjfrs_crd.yaml
- deploy/olm-catalog/container-jfr-operator-bundle/0.5.0/rhjmc.redhat.com_flightrecorders_crd.yaml
- deploy/olm-catalog/container-jfr-operator-bundle/0.5.0/rhjmc.redhat.com_recordings_crd.yaml
- deploy/olm-catalog/container-jfr-operator-bundle/container-jfr-operator-bundle.package.yaml
- deploy/role.yaml
This creates a version 0.5.0 CSV and a version 0.0.2 index. I also fixed a few minor issues I detected as well.
* Remove recordings during `make undeploy`
* Missing/old CRs in scorecard config
* Re-added `services/finalizers` to Role since this is actually used by the built-in monitoring.
> Create version 0.5.0 and minor fixes

- pkg/client/containerjfr_client.go
- pkg/controller/common/common_reconciler.go
- pkg/controller/flightrecorder/flightrecorder_controller.go
- pkg/controller/recording/recording_controller.go
With Container JFR no longer requiring a stateful connection for its commands, we can simplify the WebSocket client used by controllers in the operator. Synchronization is no longer necessary since interleaving of commands is not an issue anymore. Commands that require a target take a new TargetAddress struct as a parameter. This is an abstraction of a host/port pair. I also added some missing comments in this PR.
> Remove unneeded state and synchronization for Container JFR client

- Makefile
This PR simply reorders the `oc delete` commands in `undeploy`. This avoids deleting the operator deployment before any created recordings, and requires you to manually remove the finalizer from those.
> Reorder undeploy target to better handle recordings

- README.md
Operator SDK can fail to build the operator with errors like `unsupported type invalid type for invalid type...` if the user does not have the `GOROOT` environment variable set. This PR adds defining `GOROOT` as a build instruction to the README.
> Add GOROOT instructions to README

- go.mod
- pkg/client/command_types.go
- pkg/client/containerjfr_client.go
- pkg/controller/common/common_reconciler.go
- pkg/controller/common/common_utils.go
- pkg/controller/flightrecorder/flightrecorder_controller.go
- pkg/controller/flightrecorder/flightrecorder_controller_test.go
- pkg/controller/flightrecorder/flightrecorder_resources_test.go
- pkg/controller/flightrecorder/flightrecorder_suite_test.go
- pkg/controller/recording/recording_controller.go
This PR adds unit tests for the FlightRecorder controller using Ginkgo & Gomega. They work using the controller-runtime fake client to simulate the Kubernetes API server. A simple Gomega/httptest server stands in for Container JFR by expecting messages and replying with specified replies. This server code will be refactored to a common test package once I add tests for the Recording controller.
There is also a fair bit of refactoring done here in order to make the code more testable. This includes things like converting structs to interfaces and adding constructor functions with optional parameters used by the tests to mock system/random behaviour.
The tests can be run with `go test ./pkg/controller/flightrecorder/`
> Tests for FlightRecorder controller

- Makefile
- README.md
This adds a Makefile target for running the unit tests. If the ginkgo binary is detected, it will run the tests with that, which has a bit nicer output. There is also a new target for running integration-tests, which is currently just the scorecard tests. Once we get some end-to-end tests, they could be added to this target as well.
I've also updated the README for this change.
> Add/reorganize Makefile targets for running tests

- pkg/controller/recording/recording_controller.go
- pkg/controller/recording/recording_controller_test.go
- test/messages.go
- test/resources.go
This PR adds some additional tests that focus on deleted Recordings and how finalizers are used to perform cleanup. One fix in this PR is to return an error and requeue when the `delete` command fails.
> Add tests for recording deletion

- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
See also https://github.com/rh-jmc-team/container-jfr/pull/292 for a quicker smoketest of the new version. It seems to be fully compatible with our dashboard definition and the jfr-datasource with no apparent regressions or other adjustments needed.
> Update Grafana container to 7.2.1

- pkg/controller/containerjfr/containerjfr_controller.go
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
- pkg/controller/grafana/grafana_controller.go
This PR depends on https://github.com/rh-jmc-team/jfr-datasource/pull/54. Since communication to/from jfr-datasource is only between containers in the same pod, we can restrict it to loopback traffic only. This is particularly important since this communication is unencrypted.
The fix is fairly straightforward, aside from the liveness probe. HTTP/TCP probes appear to require the port be accessible outside of the pod. I was able to use a command probe instead where the `curl` command is done within the container itself.
Fixes: #117
> Restrict jfr-datasource to pod-internal traffic

- README.md
If for some reason the user wishes to create a recording for Container JFR itself, they'll have to know how to obtain the generated credentials. I added a variable to account for ContainerJFR CRs having arbitrary names, and changed the protocol in the URL generated by the first command to HTTPS.
> Explain how to get generated JMX credentials

- pkg/controller/containerjfr/containerjfr_suite_test.go
Forgot to add a license header to the suite file.
> add license header to suite_test file

- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
I noticed when archiving a recording, that the recording also ended up in the templates directory. This is because we use the same mounted volume for both recordings and templates, and by default it's the volume's root directory that is mounted. This fix specifies the `SubPath` property for each mount, which will mount different directories within the volume.
> Use different subpaths within volume for recordings and templates

- Makefile
Fixes #127 
This will ensure that the operator is never deployed using OC without cert-manager. I am not sure if there are other ways that the operator might be used, in which case it could still fail without cert-manager?
> Add check to make sure cert-manager is available before deploying

- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
The class `OpenShiftPlatformStrategy` was moved in a recent upstream patch (rh-jmc-team/container-jfr#391), so this adjusts the environment variable that explicitly specifies this strategy should be selected. #393 is a backport of #391 for v1 and also moves the Strategy to the same location, so this applies for either version.
> Update expected platform strategy package

- Makefile
- pkg/controller/containerjfr/resource_definitions/resource_definitions.go
This updates the Container JFR image and operator version to 1.0.0-BETA5. I'll tag this commit as well. This should provide a stable option for users while we make changes leading to the 1.0 release. The catalog source will still pull in the old 0.5.0 version, but it should work. We don't want to release a new bundle until we're certain the v1beta1 API is settled.
> Update to 1.0.0-BETA5

- Makefile
- deploy/cluster_role_binding.yaml
This adds a namespace label to the ClusterRoleBinding, so when the Makefile deletes it during `undeploy`, it will only remove the binding associated with the current namespace.
> Associate ClusterRoleBinding with namespaced operator using label

- Makefile
- README.md
Currently, `make test` is failing because the unit test suite now depends on envtest. Because of this, it no longer makes sense to have a separate `test-unit` target. The unit tests should eventually make use the envtest environment, bringing them closer to integration tests. For now, I've just left them as `test-envtest`. Scorecard is the only integration-test target, so I've reduced the test targets to just `test-envtest` and `test-scorecard`, with `test` running both.
Since the scorecard tests require a running cluster and are currently failing, I've removed them as a prerequisite for the `oci-build` target.
> Fix Makefile test targets

- Makefile
- README.md
This allows the user to (un)deploy the Operator to arbitrary namespaces, not only `container-jfr-operator-system`. This can be done like so:
`make DEPLOY_NAMESPACE=some_namespace deploy` (or `undeploy`)
Deployment to the current namespace would then look like `make DEPLOY_NAMESPACE=$(oc project -q) deploy`. I could also set the default value for `DEPLOY_NAMESPACE` to the current namespace, but I thought it might be better to require this to be explicit.
I tried to use the `config/default/kustomization.yaml`'s `namespace` property for this purpose with `kustomize`, but this ended up modifying the file in an unexpected way and changing it beyond simply replacing the `namespace` value. So I have simply used a piped `sed`  here, which is similar to what we did before the `1.x` migration. I …
> Deploy to arbitrary namespace

- controllers/common/resource_definitions/resource_definitions.go
ContainerJFR no longer supports this environment variable, so there is no point setting a value
> Remove USE_LOW_MEM_PRESSURE_STREAMING env var

- Makefile
- README.md
- controllers/common/resource_definitions/resource_definitions.go
- controllers/containerjfr_controller.go
- controllers/containerjfr_controller_test.go
- controllers/flightrecorder_controller.go
- controllers/flightrecorder_controller_test.go
- controllers/recording_controller.go
- controllers/recording_controller_test.go
- test/reconciler.go
- test/resources.go
- test/server.go
This PR fixes the `DISABLE_SERVICE_TLS` environment variable functionality to properly set up Container JFR without requiring cert-manager. I modified the ServiceSpecs struct to use URLs instead of strings. This allows us to pass the scheme, host and port to `NewDeploymentForCR`, which can adjust the environment variables as necessary. Right now, Routes always use some form of TLS even without cert-manager, but with incoming Ingress support, this will not be true. This PR makes the code more flexible to support that use case.
When `DISABLE_SERVICE_TLS` is set to true in the Makefile, the `deploy` and `deploy_bundle` targets use `kubectl set env` to add the environment variable to the operator deployment.
I added some tests to exercise the cases where code paths diverge when cert-manager …
> Fix DISABLE_SERVICE_TLS

- api/v1beta1/containerjfr_types.go
- api/v1beta1/flightrecorder_types.go
- api/v1beta1/recording_types.go
- bundle/manifests/container-jfr-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manifests/bases/container-jfr-operator.clusterserviceversion.yaml
Related to #150
This fixes the scorecard test `olm-crds-have-resources`.
> Add owned resources API markers

- api/v1beta1/containerjfr_types.go
- bundle/manifests/container-jfr-operator.clusterserviceversion.yaml
- bundle/manifests/rhjmc.redhat.com_containerjfrs.yaml
- config/crd/bases/rhjmc.redhat.com_containerjfrs.yaml
- config/manifests/bases/container-jfr-operator.clusterserviceversion.yaml
- controllers/common/resource_definitions/resource_definitions.go
- controllers/containerjfr_controller.go
- controllers/containerjfr_controller_test.go
This removes the `containerJfrUrl` annotation from the `Deployment` and adds a `dashboardUrl`
field to the `ContainerJFRStatus`, which is set once the controller has
set up the corresponding Service/Route.
Fixes #150
```
$ oc get -o yaml containerjfr
apiVersion: v1
items:
- apiVersion: rhjmc.redhat.com/v1beta1
kind: ContainerJFR
metadata:
creationTimestamp: "2021-04-07T14:34:21Z"
finalizers:
- rhjmc.redhat.com/containerjfr.finalizer
generation: 2
managedFields:
- apiVersion: rhjmc.redhat.com/v1beta1
fieldsType: FieldsV1
fieldsV1:
f:spec:
.: {}
f:minimal: {}
f:storageOptions:
.: {}
f:pvc:
.: {}
f:spec: {}
manager: oc
operation: Update
time: "2021-04-07T14:34:21Z"
- apiVersion: rhjmc.redhat.com/v1beta1
fieldsType: FieldsV1
fieldsV1:
f:metadata:
f:finalizers: {}
f:spec:
f:storageOptions: …
```
> Add Dashboard URL to ContainerJFR CR Status

- Makefile
This check existed before in the deploy target but got lost in the operator sdk upgrade. I added it to the deploy_bundle given it's the command I have been using, but it probably makes sense to add it to deploy as well.
> Add check in deploy_bundle to make sure cert manager is installed

- controllers/common/resource_definitions/resource_definitions.go
- controllers/containerjfr_controller_test.go
- test/resources.go
I've noticed occasionally the liveness probe will fail on the core Container JFR container during startup. There's a relatively new Startup Probe feature that's designed to be more lenient for containers that are slower to start [1]. This PR adds a startup probe with a 3 minute threshold (18 * 10s period), if the probe succeeds within this period, the liveness probe will take over, otherwise the container will be killed.
[1] https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-startup-probe
> Add startup probe to core container

- .github/workflows/ci.yaml
- Makefile
- controllers/recording_controller_test.go
This sets up GitHub Actions CI similar to what is now present in the main project and -core/-web.
The envtests currently fail. See https://github.com/andrewazores/container-jfr-operator/runs/2382208792?check_suite_focus=true for full detail. The first failure looks like this and the rest appear the same/similar:
```
setting up env vars
?   	github.com/rh-jmc-team/container-jfr-operator	[no test files]
?   	github.com/rh-jmc-team/container-jfr-operator/api/v1beta1	[no test files]
=== RUN   TestAPIs
Running Suite: Controller Suite
===============================
Random Seed: 1618846108
Will run 111 of 111 specs
{"level":"info","ts":1618846115.7619064,"msg":"Reconciling Recording","Request.Namespace":"default","Request.Name":"my-recording"}
{"level":"info","ts":1618846115.763062,"msg":"added …
```
> Set up GitHub Actions CI

- Makefile
- README.md
- bundle/manifests/cryostat-operator-manager-env_v1_configmap.yaml
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/default/image_tag_patch.yaml
- config/default/kustomization.yaml
- config/manager/imagetags.env
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- controllers/cryostat_controller.go
- hack/image_tag_patch.yaml.in
- test/reconciler.go
Builds with OSBS attempt to pin image tags to specific digests. In order to find the images used by our operator, they have to be defined in a predetermined location in the CSV [1]. In our case, this means our environment variables need to be renamed and can no longer refer to a config map for their values.
Unfortunately, Kustomize doesn't appear to have a nice way to handle this scenario. I ended up placing a template patch in our `hack` directory and using `envsubst` to fill in the image tags with the values from our Makefile. The resulting patch goes into the `config/default` Kustomize directory, which then gets picked up by the `deploy` and `bundle` targets. I'm not sure whether we should add `envsubst` to the list of dependencies in the README, or if it's considered a common enough …
> Generate Kustomize patch for image tag vars 

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
Fixes #209
Mounted directories and paths changed in latest Cryostat upstream due to additions of persisted credentials and serialized automatic rules
> Update mounted directories/paths for latest Cryostat upstream

- Makefile
- bundle.Dockerfile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/default/image_tag_patch.yaml
- config/manager/kustomization.yaml
- internal/controllers/common/resource_definitions/imagetag_generated.go
This PR updates the operator image version to `2.0.0-dev`, the `-dev` suffix indicating this version is still under development. Likewise the Cryostat image tag has been updated to `2.0.0-SNAPSHOT`. This ensures the operator's development builds always deploy the latest development build of Cryostat.
> chore(images): update image versions to latest development builds

- .github/workflows/semantic-pr.yml
Adds workflow file to use semantic-pull-request-action to enforce Conventional Commits standards. The file is identical to that in `cryostatio/cryostat`.
Relates to: #214
> ci(semantic-pr): add semantic-pull-request job

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Copy the release-drafter configuration from `cryostatio/cryostat` to generate release notes for the operator. The files have been copied as-is.
Relates: #214
> ci(release-drafter): generate release notes drafts

- .github/workflows/dependent-issues.yml
Copies the dependent-issues action configuration from `cryostatio/cryostat`.
Relates to: #214
> ci(dependent-issues): enable dependent-issues action

- .github/workflows/ci.yaml
This PR adds a Github workflow to push CI builds to Quay when PRs are merged. This is fairly similar to the implementation in the Cryostat repo, but the method for figuring out the image tag is different. This one is using Make's `--eval` argument to invoke a rule to print the `IMAGE_VERSION` Makefile variable.
The build targets for both PRs and pushes have been changed to `oci-build`, which is the same as before but also builds a container image. This slows down the job a bit, but we can maybe look into caching intermediate container layers. Another possibility is we split up the build step into different PR and push steps, where only the later does the container build.
Some example jobs using my fork and Quay repository:
PR: https://github.com/ebaron/cryostat-operator/actions/runs/105643 …
> ci(quay): push CI builds to Quay

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
Fix some spots in the CSV that were missed when bumping the version to 2.0.0-dev.
> chore(version): fix CSV metadata for 2.0.0-dev

- bundle.Dockerfile
- bundle/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/rbac/cryostat_role.yaml
- config/rbac/kustomization.yaml
- config/rbac/role.yaml
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
Currently, the operator configures the Cryostat deployment to use the operator's own Service Account. The vast majority of the permissions the operator requires are not needed by Cryostat. This PR creates a separate set of RBAC objects for Cryostat to use.
The operator creates an additional ClusterRole with permissions to create TokenReviews and SelfSubjectAccessReviews.
Each Cryostat CR gets its own:
* ServiceAccount
* Role, with read access to Endpoints and Routes
* RoleBinding to bind the Role to its ServiceAccount
* ClusterRoleBinding to bind the shared ClusterRole to its ServiceAccount
In order to ensure that the cluster-scoped ClusterRoleBinding doesn't suffer a name collision, the operator creates it with the following name: `cryostat-hhhh` where `hhhh` is SHA256 sum of the CR's …
> feat(security): create reduced permissions ServiceAccount for Cryostat

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
This PR changes the naming scheme of the ConsoleLink from using `GenerateName` to using a suffix of the SHA256 sum of the associated Cryostat CR's `namespace/name`. This ensures the ConsoleLink name is known and reproducible across reconciles, and eliminates the possibility of two instances being created due to the caching behaviour of the Kubernetes client.
Fixes: #163
> fix(openshift): ensure ConsoleLink is not duplicated

- .github/workflows/ci.yaml
- .github/workflows/release-drafter.yml
This follows the same approach taken in https://github.com/cryostatio/cryostat/pull/604. There's a conditional where the built images are only tagged and pushed as `latest` if the branch is `main`. I also updated the PR/push events to work with any vX or vX.Y branch. This should make the workflows more backport friendly.
Relates to #223
> ci(quay): apply latest tag only in main 

- .github/workflows/release-drafter.yml
Fix to avoid combining fixes from different branches into same release notes.
> ci(release-drafter): revert branches to only main

- .github/release-drafter.yml
- .github/workflows/ci.yaml
- .github/workflows/dependent-issues.yml
- .github/workflows/release-drafter.yml
- .github/workflows/semantic-pr.yml
This PR backports the contents of `.github` from `main` as-is.
Fixes: #223
> ci: sync CI workflows from main

- internal/controllers/certmanager.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/main.go
- internal/test/resources.go
This PR adds a check for the cert-manager API using the manager's RESTMapper. This is similar to how we check if the cluster is OpenShift. If cert-manager isn't disabled in the Cryostat CR and cert-manager is unavailable, the operator will emit a Warning event to communicate the problem to the user.
Viewing the Cryostat CR's events in the OpenShift Console:
Unfortunately, there's no visual indicator in the Details tab, but if the user sees nothing is happening and visits the Events tab, they'll see the cause.
Similarly, the Events show up when using `kubectl describe`:
```
$ kubectl describe cryostat cryostat-sample 
Name:         cryostat-sample
Namespace:    cryostat-operator-system
Labels:       <none>
Annotations:  <none>
API Version:  operator.cryostat.io/v1beta1
Kind: …
```
> feat(tls): emit event when cert-manager is missing

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
This PR adds some logic for OpenShift to ensure Cryostat runs under the `restricted` SecurityContextConstraint. The range of permitted `fsGroup` values is taken from the `openshift.io/sa.scc.supplemental-groups` annotation on the pod's namespace:
https://docs.openshift.com/container-platform/4.8/authentication/managing-security-context-constraints.html#security-context-constraints-pre-allocated-values_configuring-internal-oauth
I'm still unsure why Cryostat deployed to the `default` namespace isn't subject to SCCs, but this fix appears to make Cryostat work for both `default` and other namespaces.
Fixes #247
> fix(pvc): derive fsGroup from SCC annotation

- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
Fixes #245 
To test:
- Run `make deploy remove_cert_manager create_cryostat_cr IMG=<test_image>`. This results in a Cryostat CR with a finalizer applied to it, but unable to proceed due to cert-manager missing.
- Delete the Cryostat CR `make destroy_cryostat_cr`. Deletion should proceed without hanging.
> fix(finalizer): remove finalizers when objects to delete not found

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
This PR replaces the usage of `/api/v1/clienturl`, which has been removed. This is currently only used as a container health check. It still seemed to work, I'm guessing because the 404 would redirect to Cryostat's landing page. Since there's a proper `/health` endpoint, I've changed the container health check to use this instead.
Fixes #213
> fix(health): use /health for Cryostat health check

- api/v1beta1/cryostat_types.go
- api/v1beta1/flightrecorder_types.go
- api/v1beta1/recording_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- bundle/manifests/operator.cryostat.io_flightrecorders.yaml
- bundle/manifests/operator.cryostat.io_recordings.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_flightrecorders.yaml
- config/crd/bases/operator.cryostat.io_recordings.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
- config/manifests/xdescriptors_patch.yaml
This PR fixes the issue where the OLM spec descriptor would require an integer value for Recording duration. It's now a string and the description has been updated to indicate the format it should be. I've also added a proper description for each CRD, instead of "x is the schema for the x API". These are displayed to the user right away after installing the operator. I also corrected field descriptions that no longer make sense, like the event options field is no longer using the event specifier string format.
Finally, I wanted to leverage the same mechanism that lists local Secrets and Config Maps to list local FlightRecorder objects when creating a Recording. Because the FlightRecorder name is within a LocalObjectReference, I wasn't able to do this with Operator SDK's markers. I instead …
> fix(crd): fix OLM descriptors and documentation 

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
Just a case of nesting this code in a branch it shouldn't be in. I added a test case to ensure this works when TLS is disabled as well.
To test manually:
1. `make deploy IMG=<test_img> create_cryostat_cr`
2. Create a config map with a template file `kubectl create configmap my-template --from-file=custom.jfc`
3. `kubectl edit cryostat cryostat-sample`, change `spec.enableCertManager` to false and add the template to `spec.eventTemplates` [1]
4. Cryostat should not have a CA cert mounted, but the custom event template should be present.
Fixes #240 
[1] https://github.com/cryostatio/cryostat-operator/blob/main/docs/config.md#custom-event-templates
> fix(templates): templates should be mounted if TLS disabled

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller_test.go
> fix(openshift): correct annotation for topology view

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
This adds an annotation to our CSV that prompts the user to create a Cryostat CR after they install the operator. Unfortunately, there doesn't seem to be any Operator SDK integration to generate this for us, so we'll have to update it manually. The sample CR I included only sets `minimal` which is required, and `enableCertManager` which we want to explicitly set to true.
Visiting the Installed Operator after using `deploy_bundle`:
After uninstalling the operator and reinstalling from the CatalogSource. A similar workflow to installing from OperatorHub:
Test bundle image for convenience: `quay.io/ebaron/cryostat-operator-bundle:init-res`
Fixes #257
> build(csv): add initialization-resource annotation

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/main.go
- internal/test/resources.go
This PR adds the `CRYOSTAT_PLATFORM` and `CRYOSTAT_AUTH_MANAGER` environment variables when running on OpenShift. This also changes the OpenShift detection mechanism to not use the caching client to hopefully avoid situations like #210, but I have not encountered it again since filing.
Fixes #273, #210
> fix(openshift): force platform/auth on OpenShift

- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/default/image_pull_patch.yaml
- config/default/kustomization.yaml
- hack/image_pull_patch.yaml.in
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller_test.go
Uses a regular expression to check image tags for the following suffixes:
* latest
* SNAPSHOT
* dev
* BETA[0-9]+
If any of the above are found the pull policy for that image will be set to `Always`.
For the operator controller deployment, this is done using a Kustomize patch that is updated by the Makefile depending on the regex test. For the operand images, this same check is done in resource_definitions.go when creating the Deployment spec.
Fixes: #254
> feat(deploy): use Always pull policy for development images 

- README.md
- docs/api.md
- internal/controllers/common/common_reconciler.go
- internal/test/handlers.go
> fix(auth): Encode auth bearer token

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
This modifies the deployment spec to only set `CRYOSTAT_SSL_PROXIED` when cert-manager is disabled, but the Route/Ingress use TLS. I've added a test for this scenario with Ingress, currently Routes are always created with TLS.
Related to: #293
> fix(deploy): set CRYOSTAT_SSL_PROXIED only for TLS ingress/route

- docs/config.md
Fixes #311 
Since users are responsible for configuring the Ingress configurations, I added the recommended annotations in the readme.
> fix(ingress): Recommend Ingress timeout as 3600s

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
Adds a subpath volume mount using the PVC for the probe template directory, and sets the `CRYOSTAT_PROBE_TEMPLATE_PATH` variable.
Fixes: #317
> fix(deploy): mount probe template directory

- bundle/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/rbac/cryostat_role.yaml
- config/rbac/role.yaml
- internal/controllers/cryostat_controller.go
Related https://github.com/cryostatio/cryostat/issues/717
Adds permissions needed for the backend to `list` and `delete` an `oauthaccesstoken`. 
I believe the `oc logout` command in the OpenShift docs corresponds to the cryostat frontend `POST https://oauth-server-namespace-route/logout` request that removes the session cookie stored in the OAuth server. This `/logout` call invalidates the token but does not delete any existing invalid tokens, which is why the backend needs to make a second request to delete the access token.
[OpenShift OAuth logout docs](https://docs.openshift.com/container-platform/4.9/authentication/managing-oauth-access-tokens.html#oauth-delete-tokens_managing-oauth-access-tokens)
[OpenShift OAuth endpoint for deleting access …
> feat(auth): Add logout permissions to service account

- go.mod
- go.sum
This PR uses module replacement to patch the vulnerable transitive dependency, now maintained in a fork. Once we upgrade the Operator SDK (#287), we can upgrade client-go and remove this replacement.
Fixes: #323
> build(deps): update dgrijalva/jwt-go to patched version

- docs/config.md
Related #757
This reverts commit e524857960ffdfe44eaa360e9fd215d14b968953.
Now that the server keepalive pings in https://github.com/cryostatio/cryostat/pull/792 is merged, we can remove the extra ingress annotations to extend the idle timeout.
> docs(ingress): Remove unneeded ingress timeouts

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
Set the new `CRYOSTAT_ENABLE_JDP_BROADCAST` environment variable to false, since we don't need JDP on Kubernetes/OpenShift and to avoid network multicast issues.
Fixes: #255
Related to: https://github.com/cryostatio/cryostat/issues/803
> fix(jdp): disable JDP autodiscovery

- README.md
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_flightrecorders.yaml
- bundle/manifests/operator.cryostat.io_recordings.yaml
- config/crd/kustomization.yaml
- config/crd/patches/deprecate_flightrecorders.yaml
- config/crd/patches/deprecate_recordings.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- docs/api.md
The CRD spec has properties for whether a version is deprecated and a warning string to show the user when they try to use that version. Newer controller-tools versions support these properties using marker comments, but this requires Operator SDK 1.10 and we're still quite a bit behind that (see #287). In the meantime, I've added Kustomize patches to add these properties.
Example:
```
$ kubectl get recording
Warning: operator.cryostat.io/v1beta1 Recording is deprecated; please use the Cryostat web application or the Cryostat HTTP API to manage recordings
No resources found in cryostat-operator-system namespace.
```
I didn't see this have an effect in the UI, so I've added the `operators.operatorframework.io/internal-objects` annotation to our CSV. This results in the FlightRecorder and …
> fix(api): deprecate FlightRecorder and Recording CRDs

- docs/config.md
Related #220 
I realized I forgot to update `config.md` with the `Enabled` flag after the PR review changes
> docs(storage): fix EmptyDir option example

- internal/controllers/common/resource_definitions/certificates.go
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/test/resources.go
This PR adds a [HostAlias](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) for `127.0.0.1` to a `cryostat-health.local` hostname. We add this hostname as a SAN to our self-signed certificate issued by cert-manager. This is preferred over adding the loopback address directly, since our custom hostname is unlikely to be resolvable outside of our pod.
Fixes: #351, #357 
Previous approach using `127.0.0.1` directly:
~~Currently failing due to lack of loopback address as a Subject Alternative Name:~~
```
INFO: (10.217.0.1:44504): GET /health 200 16ms
Mar 07, 2022 10:25:15 PM io.cryostat.core.log.Logger warn
WARNING: Exception thrown
java.io.IOException: javax.net.ssl.SSLHandshakeException: Failed to create SSL connection
at …
```
> fix(grafana): use loopback alias for Grafana health check

- config/default/kustomization.yaml
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
To test:
1. `make deploy create_cryostat_cr IMG=quay.io/cryostat/cryostat-operator:2.0.0 CORE_IMG=quay.io/cryostat/cryostat:2.0.0`
2. `kubectl patch deploy cryostat-operator-controller-manager -p '{"spec": {"template": {"spec": {"containers": [{"name": "manager", "image": "quay.io/ebaron/cryostat-operator:sa-upgrade-01"}]}}}}'`
3. `kubectl set env deploy cryostat-operator-controller-manager RELATED_IMAGE_CORE="quay.io/cryostat/cryostat:2.1.0-SNAPSHOT"`
4. After a short time, verify the Service Account is updated with the annotation, and that you can log into Cryostat.
Fixes: #382
> fix(sa): update existing service account

- Makefile
> refactor(makefile): Rename the IMG env var to OPERATOR_IMG

- Makefile
- api/v1beta1/groupversion_info.go
- internal/controllers/suite_test.go
- internal/main.go
Resolves #81 
Added a script to check and add license header to source files if needed. Run `make add-license`.
We are using `addlicense v1.0.0` from https://github.com/google/addlicense.
> feat(license): add license header checking script

- docs/config.md
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
Related to #440 
Updated config docs with permanent links to permission mapping files.
Added missing custom cluster-role in unit tests for auth-properties.
> fix(auth-properties): update docs links and add missing custom cluster-role in tests

- .gitignore
Related #438 
Related #430 
Catalog build generates a temporary directory that should not be checked into git.
> fix(gitignore): ignore bundle tmp directory from catalog build

- Makefile
- bundle/tests/scorecard/config.yaml
- config/scorecard/kustomization.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/custom.config.yaml
- config/scorecard/patches/olm.config.yaml
- go.mod
- go.sum
- hack/custom.config.yaml.in
- internal/images/custom-scorecard-tests/.gitignore
- internal/images/custom-scorecard-tests/Dockerfile
- internal/images/custom-scorecard-tests/bin/entrypoint
- internal/images/custom-scorecard-tests/bin/user_setup
- internal/images/custom-scorecard-tests/main.go
- internal/images/custom-scorecard-tests/rbac/scorecard_role.yaml
- internal/images/custom-scorecard-tests/rbac/scorecard_role_binding.yaml
- internal/images/custom-scorecard-tests/rbac/scorecard_service_account.yaml
- internal/test/scorecard/tests.go
This adds the first custom scorecard test for the operator. This test is pretty basic, it just verifies that the operator deployment becomes available. It should help to serve as a simple smoke test to ensure that the operator can at least start.
I followed the instructions in the Operator SDK guide on custom scorecard tests for the most part. [1] The sample test image for Tekton was also a useful resource [2]. The tests run in a separate namespace with the operator bundle installed and RBAC objects used by the test pod created.
To test it out:
1. Build the custom scorecard test image and push to Quay.
```
export CUSTOM_SCORECARD_IMG="quay.io/<your name>/cryostat-operator-scorecard:some-unique-tag"
make scorecard-build 
podman push "$CUSTOM_SCORECARD_IMG"
```
2. Generate bundle and push …
> test(scorecard): add scorecard test for operator availability

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/controllers/services.go
Unfortunately it's not possible to add a regression test for this while using the fake client (see #448). Although after removing any side effects modifying `spec.reportOptions`, the segfault occurs as expected in the tests. Adding the nil-check in `NewCoreContainer` fixes it.
Fixes: #447
> fix(reports): add nil-check and remove side effects

- Makefile
Related to #430 
Specified `--ignore-not-found` for any `$(KUBE_CLIENT) delete` calls.
> fix(makefile): use ignore-not-found flag when deleting resources

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
The primary difficulty with this fix is that OpenShift < 4.11 does not permit you to set `seccompProfile` by default. Following the discussion in https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/1417, I decided to take the following approach with this PR.
For the operator deployment:
- Set `runAsNonRoot` and `seccompProfile` in the pod security context. This is not backwards compatible with OpenShift < 4.11. In the downstream release, we will have to remove `seccompProfile` to support these versions. The `restricted-v2` Security Context Constraint (SCC) will set the `seccompProfile` for us when it is necessary. The alternative is not being compliant on standard Kubernetes, which does not have a SCC mechanism. The end result will be upstream releases will …
> fix(security): support restricted pod security standard

- internal/controllers/common/common_utils.go
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/controllers/rbac.go
- internal/controllers/routes.go
- internal/test/resources.go
This is mostly refactoring RBAC reconciling logic into a separate `rbac.go` file. This PR also ensures that Roles, RoleBindings and ClusterRoleBindings created by the operator are kept up-to-date across operator upgrades, and includes new test cases to exercise this. There are a couple of other changes here:
1. The reports pod now uses the "default" Service Account instead of the Cryostat one. The reports generator doesn't require access to the Kubernetes API, so the elevated permissions given to Cryostat aren't necessary here.
2. Instead of controlling the value of `AutomountServiceAccountToken` in the Service Account, we simply set this to true for the Cryostat pod template. Cryostat depends on its Service Account token being mounted upon startup. The definition in the Pod spec takes …
> feat(rbac): update operator-controlled RBAC objects

- Makefile
Fixes #459
- remove very outdated sample app 2
- use updated vertx-fib-demo
- patch service for port name
- apply container limits to sample app
> chore(samples): update sample app definitions

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
This fixes a panic in the reports scheduling options when the main Cryostat scheduling options is not also set. This is caused by an incorrect nil-check. This also fixes a few problems in the reports tests where they did not test what they appeared to be testing.
Related to: #340
> fix(reports): fix panic in reports scheduling

- internal/controllers/cryostat_controller.go
- internal/main.go
This updates the kinds of objects that the controller watches to ensure that any change to an owned object triggers a reconcile. The cert-manager APIs pose a slight complication since if the resource types do not exist in the Kubernetes API server, the controller will fail to start.
I modified the OpenShift detection logic to also test for cert-manager. Unfortunately, there's no way yet to dynamically update the list of watched object types (https://github.com/kubernetes-sigs/controller-runtime/issues/1884). This means that if the user installs cert-manager after the controller has started, they will have to redeploy the operator to pick up that change.
I changed the setup from using the `Watches` method to the newer `Owns` which is recommended for this purpose.
Fixes: #415
> fix(watches): update object types watched by controller

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
This PR modifies the Deployment update code to detect when the immutable selector has changed. When this is detected, the operator deletes the deployment and recreates it. With this change it should be possible to upgrade from 2.0 to 2.2, the deployment selectors were changed in 2.1. I built a catalog image to help test this upgrade scenario: `quay.io/ebaron/cryostat-operator-catalog:selector-fix-01`.
To test:
1. Create the following objects:
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: cryostat-catalog
namespace: openshift-marketplace
spec:
sourceType: grpc
image: quay.io/ebaron/cryostat-operator-catalog:selector-fix-01
displayName: Cryostat Catalog
publisher: Cryostat Authors
updateStrategy:
registryPoll:
interval: 10m
```
```yaml
apiVersion: …
```
> fix(deploy): recreate deployment if selector changed

- docs/config.md
Related to #437 
Updated config docs for default resource requests. And fix minor typos.
> docs(resources): document default resource requests

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/test/resources.go
There are two bugs that occur due to replicas contending for access to the credentials database, and replicas on different nodes competing for the PVC itself. Cryostat is currently meant to work as a single replica, but during rolling updates there could be two simultaneously.
To avoid these issues, we're changing the deployment strategy from the default of `RollingUpdate` to `Recreate`. As a result there will be some brief downtime in response to upgrades or configuration changes. The other change is the operator managing the `Replicas` field of the main Cryostat deployment. This is to ensure that the replica count stays at 1 to avoid the above bugs.
To test:
1. `make deploy create_cryostat_cr OPERATOR_IMG=....`
2. `kubectl edit cryostat cryostat-sample`. Change some field such as …
> fix(deploy): use recreate strategy and 1 replica

- internal/controllers/cryostat_controller_test.go
- internal/test/reconciler.go
- internal/test/resources.go
This PR is long, but a lot of the changes are a result of changing functions to methods. I've added a `TestResources` struct that is embedded into the `cryostatTestInput` used by the controller tests. Several fields have moved to the `TestResources` type where it makes sense: `minimal`, `tls`, etc. These would be fields that have some effect on the creation of the test objects. In addition to this, a new `namespace` field is added. Modifying this field affects the namespace of all subsequently created test objects.
By changing the test object creation from functions to methods, I've been able to reduce the parameter bloat, which hopefully results in more readable tests. I've tried quite a few iterations of this refactoring, before settling on this approach. Let me know what you think. …
> test(resources): multi-namespace support for test resources

- internal/controllers/certmanager.go
- internal/controllers/common/tls.go
- internal/controllers/cryostat_controller.go
- internal/controllers/cryostat_controller_test.go
- internal/test/clients.go
- internal/test/resources.go
This PR moves the logic for updating certificate and route statuses from `reconcileCryostatFully` to a custom client implementation. This client triggers the update upon the first successful `Get` call. This happens after the object has been created, so we're still exercising the `RequeueAfter` code paths.
The advantage here is that we can simplify how we do reconciles in the tests themselves. I've changed `reconcileCryostatFully` to use Gomega's `Eventually` to call `Reconcile` asynchronously until it no longer re-queues or times out. This allows us to use `reconcileCryostatFully` in more places.
I also removed an unnecessary `Get` call for the certificate in `common/tls.go`. We already have the certificate in memory, and this was triggering the certificate update logic earlier than …
> test(reconcile): simulate controllers with custom client

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/cryostat_controller_test.go
The implementation change is just setting the install mode to `true`. I've updated the tests to create two Cryostat instances in different namespaces and check that the proper resources are created for each.
I created a catalog image to test this change. You can use it by creating the following catalog source.
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: cryostat-all-ns
namespace: openshift-marketplace
spec:
sourceType: grpc
image: quay.io/ebaron/cryostat-operator-catalog:all-ns-01
displayName: Cryostat Test
publisher: grpc
```
The all namespaces install mode should be set as default:
Try creating Cryostat CRs in different namespaces:
I noticed some difficulty with Cryostat missing targets. I'm not sure if that's related to this PR or not.
Fixes: …
> feat(csv): enable AllNamespaces install mode

- api/v1beta1/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
This manually specifies the `displayName` for `JmxCredentialsDatabaseOptions` option. I have built a bundle image for checking these changes here: 
```
quay.io/thvo/cryostat-operator-bundle:2.3.0-pr517
```
Fixes #516
> chore(api): capitalize JMX credentials DB display name

- internal/main.go
This changes the discovery approach from looking up all APIResources to just looking up those we need to detect OpenShift and cert-manager.
Fixes: #529
> fix(discovery): look up API resources individually

- Makefile
- README.md
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/rbac/role.yaml
- internal/controllers/clustercryostat_controller.go
- internal/controllers/cryostat_controller.go
This fixes `make deploy` to work across multiple namespaces. Permissions for resources created by the operator are converted from single-namespace to cluster-wide permissions. It also adds `make create_clustercryostat` and `destroy_clustercryostat` analogues to the existing targets for the Cryostat CR. `WATCH_NAMESPACE` is set to the empty string, which signals the manager to watch all namespaces.
Fixes: #522
> build(make): update Makefile targets to support ClusterCryostat

- docs/multi-namespace.md
This PR adds a separate `docs/multi-namespace.md` that only highlights the differences compared to the existing Cryostat CRD. It includes references to `docs/config.md` that point out that all existing configuration can be used with the ClusterCryostat CRD as well.
Fixes: #521
> docs(api): document ClusterCryostat API

- internal/controllers/clustercryostat_controller_test.go
- internal/controllers/configmaps.go
- internal/controllers/cryostat_controller.go
- internal/controllers/openshift.go
- internal/controllers/rbac.go
- internal/controllers/reconciler.go
- internal/controllers/reconciler_test.go
- internal/test/clients.go
- internal/test/resources.go
This PR addresses potential conflicts between the Cryostat and ClusterCryostat CRDs when they refer to the same name and namespaces. To handle the majority of objects managed by the respective controllers, they now create a Config Map at the beginning of their reconcile method which acts as a lock. Whichever controller creates and owns this Config Map first gets to proceed. This works for anything created in the installation namespace.
For the target namespaces, the only objects that are created are role bindings. These will reject updates since they can only be controlled by one owner object.
In both of these cases, we detect if we attempt to control an already controlled object and emit a warning Event that should give the user enough information as to why their CR can't proceed.
In the …
> fix(api): prevent overwriting objects when names conflict

- api/v1beta1/clustercryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_clustercryostats.yaml
- config/crd/bases/operator.cryostat.io_clustercryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
This adds a warning about multi-tenancy to the target namespaces field. It links to the documentation in this repo for more details. The tag does not exist yet, but will upon 2.3.0 release. For now you can replace `v2.3.0` with `main` to test it out.
Fixes: #542
> fix(api): add multi-tenancy warning to description

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/pull_request_template.md
Fixes #553 
See https://github.com/maxcao13/cryostat-operator/issues/new/choose for Issue templates
See https://github.com/maxcao13/cryostat-operator/compare/main...maxcao13:cryostat-operator:cryostat-v2.1 and press `Create Pull Request` to see the PR template
This uses the new Beta Github [Issue Forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) 
cryostat and cryostat-web do not use this yet, but I decided to try it since this is a different repo. One thing that isn't that great is that I can't change the issue template `labels` to be 
like the other repos. They are stuck at 
for now until or if Github decides to change this.
> chore(github): add pr and issue templates

- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- internal/images/custom-scorecard-tests/rbac/scorecard_role.yaml
- internal/test/scorecard/tests.go
Fixes: #559 
If an expected deployment doesn't become available within the time limit (10m), log the conditions and warning events of the deployment, its replica sets and pods.
I also increased the timeout for the scorecard tests since we use timeouts for blocking operations inside the tests themselves and I've found that if the Scorecard timeout occurs then we lose logs.
If Scorecard tests are run on a cluster where we don't have access to logs, it would be helpful to include as much output as possible for why the tests failed.
I built a test bundle and scorecard image from this PR. I also set the `CORE_IMG` to `quay.io/ebaron/cryostat:does-not-exist` in order to cause an error during the test.
`make test-scorecard …
> test(scorecard): log workload conditions/events upon failure

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
Fixes: #562 
Changes the `initialization-resource` annotation back to the Cryostat CRD, as it was in 2.2.
We have to choose one of the two CRDs, and at this time, the old Cryostat CRD makes more sense as a default case.
1. Build a bundle image.
2. Deploy the bundle image.
3. Visit the installed operator in OpenShift Console.
4. You should be prompted to create a Cryostat CR.
> fix(csv): use Cryostat CR as initialization resource

- docs/config.md
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
Fixes: #564 
Lowers the default CPU resource request for the Grafana container from 1 CPU to 0.1 CPU.
This brings the Grafana container in line with what's deployed by the [Grafana Operator](https://github.com/grafana-operator/grafana-operator) by default. It allows Cryostat to run on more resource constrained clusters without manually lowering the resource requests when creating the Cryostat CR.
1. Deploy operator
2. Create a CR with all defaults
3. Inspect Grafana container's resource requests. It should be `100m` for CPU.
> fix(deploy): lower default Grafana CPU request

- .github/workflows/ci.yaml
- Dockerfile
- README.md
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- go.mod
- internal/images/custom-scorecard-tests/Dockerfile
Fixes: #568 
Modifies Dockerfiles, Makefile, go.mod and GitHub workflow to use Golang 1.20.
This ensures that the Golang version used to build the Cryostat Operator remains supported throughout the lifecycle of Cryostat 2.3.
1. `make deploy create_cryostat_cr OPERATOR_IMG=quay.io/ebaron/cryostat-operator:golang-1.20`
2. `make test-scorecard BUNDLE_IMG=quay.io/ebaron/cryostat-operator-bundle:golang-1.20`
> build(go): upgrade to Golang 1.20

- api/v1beta1/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_clustercryostats.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_clustercryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/secrets.go
Related to #573 
Update user displayName and description of the credential database option field. 
Though, with users creating or inspecting Cryostat with CLI. This descriptions are updated but the old field is visible.
```bash
$ oc explain cryostat.spec.jmxCredentialsDatabaseOptions
KIND:     Cryostat
VERSION:  operator.cryostat.io/v1beta1
RESOURCE: jmxCredentialsDatabaseOptions <Object>
DESCRIPTION:
Options to configure the Cryostat application's credentials database.
FIELDS:
databaseSecretName	<string>
Name of the secret containing the password to encrypt credentials database.
```
See #573
> fix(crd): remove mentions of JMX in credential database

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- internal/main.go
Fixes: #580 
Disable cache for RoleBinding objects when not installed cluster-wide. The cache only stores objects in the namespaces listed in `WATCH_NAMESPACE`, this bypasses the cache for RoleBindings to use the API server directly.
Prevents OwnNamespace operator installs from breaking when users create a ClusterCryostat.
1. Have 3 namespaces (adjust naming as you wish): cryostat-test, test-a and test-b.
2. Install a sample application into test-a and test-b.
3. Install the operator with this fix using the `OwnNamespace` install mode:
`make deploy_bundle BUNDLE_INSTALL_MODE=OwnNamespace BUNDLE_IMG=quay.io/ebaron/cryostat-operator-bundle:disable-cache-rbac-01`
4. Create a ClusterCryostat in cryostat-test, targeting test-a and test-b:
```yaml …
```
> fix(rbac): bypass cache when reading RoleBindings

- internal/test/scorecard/tests.go
Related to #444 
Update tests to support running on k8s clusters. This is added with the assumption that the k8s cluster has Ingress enabled.
This allows testing other than OCP clusters (i.e. CI with kind).
1. Launch `kind` with Ingress enabled and OLM installed.
2. Install Cert Manager
3. Deploy operator bundle
4. Run scorecard
> test(scorecard): enable scorecard on k8s

- .github/kind-config.yaml
- .github/workflows/ci.yaml
- .gitignore
- .mergify.yml
- Makefile
Fixes: #227, #493 
Depends on #589
- Add CI to push bundle and scorecard image (if not exists) to quay.io.
- Add CI to run envtest and scorecard.
See #227, #493
See CI job status:
- https://github.com/tthvo/cryostat-operator/actions/runs/5042553727/jobs/9043312859
- https://github.com/tthvo/cryostat-operator/actions/runs/5042639850/jobs/9043480603?pr=4
Push jobs on `main` push is failing on my repo since it does not have access to `cryostat/cryostat` but build steps seems to work fine.
We also need to remove checks for `build Expected — Waiting for status to be reported ` as CI job name is changed.
> feat(ci): setup CI to push scorecard, bundle images and run scorecard

- .github/workflows/ci.yaml
Related to: #588 
Fix scorecard check command so that new tag can trigger rebuilds.
New scorecard tag should trigger CI builds but its failing because check command is misbehaving.
> fix(ci): new scorecard tag should trigger CI builds

- .github/workflows/ci.yaml
Related to #588 
Update checkout action to point to the correct ref on pull requests. In case of `main` push, the `github.event.pull_request` will be undefined and env vars are unset -> checkout action will use default values to point to upstream main.
Tests must be run on correct refs.
PR: https://github.com/tthvo/cryostat-operator/actions/runs/5204207131/jobs/9388118038?pr=5
Main: https://github.com/tthvo/cryostat-operator/actions/runs/5204160566/jobs/9388004556
> fix(ci): ci should checkout correct ref

- internal/controllers/openshift.go
- internal/controllers/reconciler_test.go
- internal/test/resources.go
Related to https://github.com/cryostatio/cryostat/issues/1489
Depends on https://github.com/cryostatio/cryostat-web/pull/1059
Remove the reconciler logics that modify the api-server to add cryostat application URL as allowed CORS origins.
https://github.com/cryostatio/cryostat-web/pull/1059 will submit form on the web client to clear login session. This removes the requirement for making CORS request.
> chore(oauth): remove modifications to OpenShift api-server

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
Related to: https://github.com/cryostatio/cryostat/issues/1329
Bumps custom Scorecard image tag.
To trigger CI to build and push multi-arch (amd64, arm64) images.
> chore(scorecard): bump Scorecard tag to trigger arm64 build

- .github/workflows/ci.yaml
- .github/workflows/image-cleanup.yml
Fixes: #603 
This change allows the removal of test images after the PR is closed
This change is helpful because it helps get rid of polluted dangling images
2. *...*
> feat(ci): clean up test images after closing PRs

- .github/workflows/ci.yaml
Related to #609 
- Fixed missing scorecard image tags while pushing to `ghcr.io`.
- Also, refactor image tag computing into a separate for the `scorecard-test` job. This eases future refactoring when we implements `/build_test` command here.
- CI tag: `ci-${COMMIT_SHA}`
- Pull Request Tag: ` pr-${PR _NUMBER}-${COMMIT_SHA}`
CI Fail: https://github.com/cryostatio/cryostat-operator/actions/runs/6004320255/job/16284655157
> ci(scorecard): fix missing image tags

- Makefile
Related to https://github.com/cryostatio/cryostat-operator/pull/450
Label namespace to `warn` and `audit` violations to restricted standards. This is similar to SCC on  OpenShift 4.11 or 4.12 (if I remember correctly).
Ideally, we would want to set enforcing mode but there is an issue with the bundle pod (ie. `runAsNonRoot` is not `true`) - See below.
Scorecard pods are run with security contexts conforming to restricted standards.
https://github.com/cryostatio/cryostat-operator/blob/5c3769f5a2823847214528fb655b297d688dac14/Makefile#L141
However, scorecard namespace is not labelled to enforce such restricted policy.
> feat(scorecard): add psa labels for scorecard namespace

- README.md
Fixes: #631 
* Edited existing badge from `ci.yml` to `build-ci.yml`
* Added another badge to `test-ci-push.yml`
* There was no `ci.yml` anymore.
* Open `README.md` and click on the badges.
> docs(readme): build-ci and test-ci-push badges

- .github/workflows/test-ci-reusable.yml
- Makefile
- README.md
- bundle.Dockerfile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_clustercryostats.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/crd/bases/operator.cryostat.io_clustercryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
Fixes: #614 
This change upgrades Operator SDK v1.28.0. to the newest available version at the moment (v1.31.0.)
upgrade to the latest available version
2. *...*
> chore(build): upgrade Operator SDK to v1.31.0

- .github/workflows/dependent-issues.yml
- .github/workflows/release-drafter.yml
- .github/workflows/semantic-pr.yml
- .github/workflows/test-ci-command.yml
- .github/workflows/test-ci-reusable.yml
Fixes: #613 
Replace GHCR_PR_TOKEN with GITHUB_TOKEN
Raised initially by Thuan
2. *...*
> feat(ci): replaced GHCR_PR_TOKEN with GITHUB_TOKEN

- Makefile
Related to #629 
Remove leading space when using conditional directives.
Looks like leading tab is causing the variable to be undefined. And `kubectl delete` is complaining.
> fix(makefile): fix ignore-not-found is not defined

- .github/workflows/build-ci.yml
- .github/workflows/test-ci-command.yml
- .github/workflows/test-ci-reusable.yml
Fixes: #638 
This change updates GitHub actions node version from 12 that is deprecated to v16
Running workflows produces warning of the deprecated node 12 version
2. *...*
> feat(ci): update github actions to node 16

- .github/workflows/test-ci-reusable.yml
Fixes: #645 
Remove manual cache actions and use automatic cache from `setup-go@v4`.
References: https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
See #645
> ci(controller-test): remove manual cache actions 

- .github/CODEOWNERS
- .github/dependabot.yml
Fixes: #537 
Configure dependabot updates to ignore k8s related deps. These deps will be upgrade with operator-sdk upgrades.
See #537
> ci(dependabot): configure dependabot updates

- internal/controllers/insights/insights.go
- internal/controllers/insights/insights_controller.go
- internal/controllers/insights/setup.go
- internal/controllers/insights/setup_test.go
Related to: https://github.com/cryostatio/cryostat/issues/1763
Adds the HTTP port to the `INSIGHTS_PROXY` environment variable in the Cryostat deployment.
Agents attempt to incorrectly connect to the default port of 80.
> fix(insights): add port to INSIGHTS_PROXY

- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/insights/insights_patch.yaml
- config/rbac/role.yaml
- internal/controllers/const_generated.go
- internal/controllers/insights/apicast.go
- internal/controllers/insights/insights.go
- internal/controllers/insights/insights_controller.go
- internal/controllers/insights/insights_controller_test.go
- internal/controllers/insights/test/resources.go
- internal/main.go
- internal/tools/const_generator.go
Related to: https://github.com/cryostatio/cryostat/issues/1763
Add a specific User-Agent header to route traffic through the UHC Auth Proxy: https://github.com/RedHatInsights/uhc-auth-proxy/commit/663067c681e0557cedc4358e62f130ab1dff6085
Traffic not routed through the UHC Auth Proxy requires a JWT Bearer token, which the cloud.openshift.com token is not.
> fix(insights): set User-Agent header for UHC Auth Proxy

- .github/workflows/test-ci-command.yml
- .github/workflows/test-ci-push.yml
- .github/workflows/test-ci-reusable.yml
> ci(status): add status check for tests

- Makefile
Related to #541 
Use `CLUSTER_CLIENT` instead of `oc` to apply the k8s yamls.
`create_clustercryostat_cr` is failing with `oc not found` error when using with `kubectl`.
> chore(makefile): use CLUSTER_CLIENT instead of oc

- Makefile
Related to #668 
Added an option (Makefile) to generate the bundle with OpenShift manifests. Default to Kubernetes.
Avoid the need to manually edit the kustomize file when building bundles for OCP. I used this to check out the #668  so I thought it would be nice to have it here. 
```bash
BUNDLE_MODE=ocp make bundle
```
> chore(makefile): option to generate bundles with quickstart on ocp

- config/openshift/cryostat-quickstart.yaml
Related to: https://github.com/cryostatio/cryostat-operator/pull/668
Fixes indentation and fields. Removes explicit summary of tasks since this is already generated when working through the Quickstart. Removed placeholder text and summary fields. Generally followed the example of our existing quickstart: https://github.com/openshift/console-operator/pull/770
When installing the bundle with the Quickstart included, I see the following errors:
```
unknown field "spec.tasks[0].review.summary", unknown field "spec.tasks[1].review.summary", unknown field "spec.tasks[2].conclusion", unknown field "spec.title"
```
1. `oc create -f config/openshift/cryostat-quickstart.yaml`
2. Access the Quickstart from the Help menu in the OpenShift Console.
> fix(openshift): update Quickstart text/formatting

- internal/controllers/certmanager.go
- internal/controllers/clustercryostat_controller_test.go
- internal/controllers/common/finalizer_utils.go
- internal/controllers/common/resource_definitions/certificates.go
- internal/controllers/reconciler.go
- internal/controllers/reconciler_test.go
- internal/test/clients.go
- internal/test/resources.go
> feat(cert): add cryostat CA cert to target namespaces

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- go-license.yml
- hack/custom.config.yaml.in
- internal/images/custom-scorecard-tests/main.go
- internal/test/scorecard/clients.go
- internal/test/scorecard/common_utils.go
- internal/test/scorecard/tests.go
Fixes: #503 
Updates the Cryostat CR from default emptyDir storage to PVC storage and checks if the resulting redeployment is as expected.
regular steps to check scorecard tests
> test(scorecard): scorecard test for Cryostat CR configuration changes

- .github/workflows/build-ci.yml
Related to #698 
Updated CI to get scorecard tag from the 2nd test stage (custom scorecard) added in #698.
The scorecard image is being built with tag `null` on upstream main.
CI: https://github.com/cryostatio/cryostat-operator/actions/runs/8161839436/job/22311468196
Quay: https://quay.io/repository/cryostat/cryostat-operator-scorecard?tab=tags
> fix(build-ci): fix scorecard image tag returned as null

- api/v1beta1/cryostat_conversion.go
- api/v1beta1/cryostat_conversion_test.go
- api/v1beta2/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- config/samples/operator_v1beta2_cryostat.yaml
- docs/config.md
- internal/controllers/certmanager.go
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/ingresses.go
- internal/controllers/reconciler.go
- internal/controllers/reconciler_test.go
- internal/controllers/routes.go
- internal/controllers/secrets.go
- internal/controllers/services.go
- internal/test/conversion.go
- internal/test/resources.go
Fixes: #728 
- Removed minimal mode support in v1beta2 API.
- I left the network resources (i.e. ingress, route) for grafana intact utill #727 that deploy cryostat3 behind proxy.
See #728 
Set up and rebuild images:
```bash
export IMAGE_NAMESPACE=quay.io/<namespace>
export IMAGE_VERSION=3.0.0-remove-minimal
make oci-build bundle bundle-build
podman push quay.io/<namespace>/cryostat-operator:$IMAGE_VERSION
podman push quay.io/<namespace>/cryostat-operator-bundle:$IMAGE_VERSION
make deploy_bundle
```
**With OpenShift:**
```bash
yq .spec.minimal=true config/samples/operator_v1beta1_cryostat.yaml | oc apply -f -
```
**With k8s (and Nginx Ingress Controller):**
Create a CR with the following specs in this …
> chore(api): remove minimal option from CR spec

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- internal/images/custom-scorecard-tests/rbac/scorecard_role.yaml
- internal/test/scorecard/common_utils.go
- internal/test/scorecard/logger.go
- internal/test/scorecard/tests.go
Fixes: #750 
Added goroutines to asynchronously fetch container logs and appended them to test results.
The idea works very nicely: https://gist.github.com/tthvo/fc6b06c948e410c3048610498b0ae09c. Maybe additional formatting is needed?
See #750 
```bash
export IMAGE_NAMESPACE=quay.io/thvo
make scorecard-build bundle bundle-build && \
podman push $IMAGE_NAMESPACE/cryostat-operator-bundle:2.5.0-dev && \
make test-scorecard 
```
> test(scorecard): add container logs to scorecard results

- .github/workflows/test-ci-command.yml
Related to #744 
Add `pull-requests: write` so when a test fails, a comment can be made on the PR.
> fix(CI): add permission to publish comment when ci fails

- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- config/scorecard/patches/custom.config.yaml
- internal/controllers/const_generated.go
- internal/controllers/cryostat_controller.go
- internal/controllers/insights/test/resources.go
- internal/tools/const_generator.go
Fixes: #761 
Bumps the operator and scorecard image versions to 3.0.0-dev. Also restores the Go Generate comment, which was accidentally removed along with the ClusterCryostat controller.
Doesn't conflict with CI builds from the main branch.
> chore(version): bump version to 3.0.0-dev

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- hack/custom.config.yaml.in
- internal/images/custom-scorecard-tests/main.go
- internal/images/custom-scorecard-tests/rbac/scorecard_role.yaml
- internal/test/scorecard/clients.go
- internal/test/scorecard/common_utils.go
- internal/test/scorecard/tests.go
Fixes: #539 
Multi-namespace scorecard test for 2.x operator
> test(scorecard): multi-namespace scorecard test

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- internal/test/scorecard/common_utils.go
- internal/test/scorecard/logger.go
- internal/test/scorecard/tests.go
Related to #758 
- Extended container logging goroutine to support report sidecar.
- I was not sure if you meant to request it to be added in other tests too so I added only to report test now. Please let me know if you need it in others too :D 
- Formatted log output with some headers that include namespace, pod name, and container name.
> It would be cool in a follow up PR if we could get this working for other tests too. Like for the reports test, it would good to see the logs from the reports container too.
_Originally posted by @ebaron in https://github.com/cryostatio/cryostat-operator/pull/758#pullrequestreview-1947366013_
https://gist.github.com/tthvo/3ec9f94f55aa1a376f4d2bc18069d5d7
> test(scorecard): add container logs for report sidecard test

- config/manager/kustomization.yaml
- config/manager/patches/force_openshift_patch.yaml
- internal/main.go
Fixes #805 
Provided an optional flag to overwrite platform discovery to set openshift to `true`. 
With these changes, I try to utilize kustomize. I can try automatically add the patch the deployment like below but it looks not so nice:
```make
cd config/manager && $(KUSTOMIZE) edit add patch \
--path patches/force_openshift_patch.yaml \
--group apps \
--version v1 \
--kind Deployment \
--name controller-manager \
--namespace system
```
But things can be much easier with `yq`. What do you think? 
See #805 
- Uncomment the patch in `manager.yaml`
- `make oci-build bundle bundle-build`
- Push the controller and bundle images.
- Launch a local `kind` cluster and logs the controller pod. It should show the following message regardless.
``` …
```
> feat(ocp): add optional flag to force platform as openshift

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/certmanager.go
- internal/controllers/common/resource_definitions/certificates.go
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/configmaps.go
- internal/controllers/const_generated.go
- internal/controllers/constants/constants.go
- internal/controllers/reconciler.go
- internal/controllers/reconciler_test.go
- internal/controllers/routes.go
- internal/controllers/services.go
- internal/test/clients.go
- internal/test/resources.go
Based on #809
Depends on #809
Related to #710
1. Check out PR, build with `OPENSHIFT_OAUTH_PROXY_IMG=quay.io/andrewazores/openshift-oauth-proxy:test-14`. Deploy, then create a Cryostat CR. **Don't** set `DISABLE_SERVICE_TLS`, and **do** leave `enableCertManager:true`!
2. Verify that one Route is created pointing at port `4180`, which is the authproxy HTTP(S) port. It should redirect HTTP requests to HTTPS, and then it should reencrypt HTTPS traffic from the Router edge to the authproxy service.
3. Open `http://cryostat-cryostat.mycluster.domain` in your browser. Note that the URL protocol is `http`. The Route should immediately redirect …
> feat(tls): enable TLS on authproxies

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/scorecard/patches/custom.config.yaml
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
> fix(reports): update deprecated quarkus properties

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- internal/test/scorecard/clients.go
- internal/test/scorecard/common_utils.go
- internal/test/scorecard/openshift.go
- internal/test/scorecard/tests.go
- internal/test/scorecard/types.go
Fixes: #816 
- Updated `RecordingClient` to use `v3` APIs. `v1` API calls are failing, likely due to https://github.com/openshift/oauth-proxy/issues/272 as `connectUrl` segment is invalid when passed to upstream cryostat.
- Updated GraphQL for fetching Archives.
- Updated utility to not base64 encode the Bearer token (encoding was necessary for built-in OpenShift auth-manager in v2).
- Replaced deprecated [`PollImmediateUntilWithContext`](https://pkg.go.dev/k8s.io/apimachinery@v0.28.9/pkg/util/wait#PollImmediateUntilWithContext) with `PollUntilContextCancel`.
See #816 
```bash
export PLATFORMS=linux/amd64
export IMAGE_NAMESPACE=quay.io/<namespace>
make scorecard-build bundle bundle-build && podman push …
```
> test(scorecard): fix broken scorecard tests for 3.0

- Makefile
- internal/images/custom-scorecard-tests/main.go
- internal/test/scorecard/clients.go
Fixes: #775 
Modify scorecard to allow running scorecard test locally.
- Update to use `config.GetConfig` to also pick local kube configurations (e.g. ` $HOME/.kube/config`)
- Allow overwriting bundle path with `BUNDLE_DIR`.
**Note:** This requires the cluster to be reachable from the host (e.g. local OpenShift with `crc`). Setup with `kind` and `podman` is not supported as host is not interfaced with the cluster network (but `kind` and `docker` should work).
This makes it easier to run scorecard without having to rebuild the scorecard and bundle images.
Assuming local host is properly configured to communicate with a k8s cluster. See https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client/config#GetConfig
If using `crc`:
```bash
crc …
```
> feat(scorecard): allow running scorecard test locally

- api/v1beta1/cryostat_types.go
- api/v1beta2/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/reconciler_test.go
- internal/controllers/secrets.go
- internal/test/resources.go
Related to #710 
- Moved/Added new status fields for secrets to `v1beta2` since they are only applicable in Cryostat `3.0`.
- Updated the controller to set missing status fields for database and storage secrets.
- Added kubebuilder/operator-sdk markers for status fields such that:
- Database and Storage secrets' names are also showed when `kubectl get cryostat` (default output).
```bash
NAME              APPLICATION URL                                 TARGET NAMESPACES   STORAGE SECRET                       DATABASE SECRET
cryostat-sample   https://cryostat-sample-myns.apps-crc.testing   ["myns"]            cryostat-sample-storage-secret-key   cryostat-sample-db
```
- [`xDescriptors={"urn:alm:descriptor:io.kubernetes:Secret"}`](https://github …
> feat(status): CR status for database and storage secrets

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/reconciler_test.go
- internal/test/resources.go
Fixes: #826 
- Updated the controller to consider custom secret for the database container if specified.
- Tests: Added checks to validate storage, database and auth-proxy container specs. These are previously missing.
- The AuthProxy container should have some checks for the container's arguments. For OpenShift Auth Proxy, most configs are specified using flags. Maybe, its better to split that into a separate follow-up PR. 
See #826. Tests are not yet validating the storage, database and auth-proxy containers.
Create a database secret:
```bash
cat <<EOF | oc apply -f -
apiVersion: v1
stringData:
CONNECTION_KEY: connection_key
ENCRYPTION_KEY: encryption_key
kind: Secret
metadata:
name: db-secret
type: Opaque
EOF
```
Deploy the operator and …
> fix(secret): database should use user-defined secret if specified

- README.md
- api/v1beta1/cryostat_conversion.go
- api/v1beta1/cryostat_conversion_test.go
- api/v1beta2/cryostat_types.go
- api/v1beta2/zz_generated.deepcopy.go
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/samples/sample-app-agent.yaml
- docs/config.md
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/constants/constants.go
- internal/controllers/reconciler_test.go
- internal/controllers/secrets.go
- internal/controllers/services.go
- internal/test/conversion.go
- internal/test/resources.go
- internal/test/scorecard/tests.go
> chore(jmx): remove configuration for JMX server, service, and auth secret

- api/v1beta1/cryostat_conversion.go
- api/v1beta2/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/reconciler_test.go
- internal/test/resources.go
Related to #715 
- Correct documentations for discovery fields. The field doc said the below previously though it should be the opposite.
> // When true, the Cryostat application will use the default port name jfr-jmx to look for JMX connectable targets.
> DisableBuiltInPortNames bool `json:"disableBuiltInPortNames,omitempty"`
- Updated field names to be consistent. @ebaron Is it OK to update `v1beta2`  as such? Otherwise, I can just update the docs only.
Documentation might be confusing as they state the opposite of what the fields should do.
> chore(discovery): ensure consistent names for discovery options in CRD

- Makefile
Just cleaning up the output a bit so it's easier to read. The format is still not perfect, but it's good enough. 
Related to: #775
> fix(scorecard): print newline instead of \n in local scorecard test output

- internal/controllers/common/resource_definitions/resource_definitions.go
Fixes: #838
Explicitly sets some flags on the OpenShift OAuth Proxy to prevent it from passing headers to upstream servers (Cryostat, Grafana dashboard, storage) containing Basic credentials or auth tokens which the upstreams do not use and should not have access to if they don't have a particular need.
According to https://oauth2-proxy.github.io/oauth2-proxy/configuration/alpha-config#removed-options , the `oauth2-proxy`'s equivalent flags are not accessible when using the alpha configuration. We use alpha configuration because it is the only way to turn on the `proxyRawPath` setting (https://oauth2-proxy.github.io/oauth2-proxy/configuration/alpha-config#upstreamconfig), which is the switch for this proxy to avoid the path encoding redirect …
> fix(proxy): do not pass unused credentials upstream

- internal/test/resources.go
> test(proxy): add missing args to proxy expectations

- README.md
- api/v1beta2/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/reconciler_test.go
- internal/controllers/secrets.go
- internal/test/resources.go
Fixes: #475 
Updated the reconciler logic to emit an Event to warn against mismatched secret name for database and return an approriate error.
See #475. The secret used to database encryption must not change (i.e. `databaseOptions.secretName` is immutable).
Create a secret:
```bash
cat <<EOF | oc apply -f -
apiVersion: v1
stringData:
CONNECTION_KEY: connection_key
ENCRYPTION_KEY: encryption_key
kind: Secret
metadata:
name: db-secret
type: Opaque
EOF
```
Deploy the operator and create a CR:
```bash
export IMAGE_NAMESPACE=quay.io/some-user
export IMAGE_VERSION=test-version
make oci-build bundle bundle-build
podman push $IMAGE_NAMESPACE/cryostat-operator:$IMAGE_VERSION
podman push $IMAGE_NAMESPACE/cryostat-operator-bundle:$IMAGE_VERSION
make …
```
> fix(crd): restrict database secret name to be immutable

- .github/workflows/build-ci.yml
> ci(workflow): only attempt push if repo owner is upstream project

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
Related to #726
Sets the `GRAFANA_DASHBOARD_EXT_URL` to the simple relative `/grafana/` path, rather than the full Route URL.
Since Grafana and Cryostat are now deployed together behind a common auth proxy instance, the client accesses Grafana simply by navigating to `/grafana/` on the Cryostat UI URL. This change simplifies the setup so that there are now no more references to the full Route URL in the Deployment, so it is overall more dynamic and flexible. This will support cases where the user wishes to deploy Cryostat on a custom domain or custom subpath.
> fix(grafana): use relative dashboard path

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
Related to #831 
- Bump csv minKubeVersion to 1.21.0
After #831, the minimum supported k8s version is 1.21.
Reference: https://olm.operatorframework.io/docs/best-practices/common/#provide-what-are-the-k8s-versions-supported-by-your-project
> chore(csv): bump csv minKubeVersion to 1.21.0

- api/v1beta1/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
Fixes: #879 
* Applies `deprecatedversion` marker to v1beta1 Cryostat
* Warns users that they should be using the v1beta2 version and the v1beta1 version is subject to future removal
1. Install new CRDs
2. 
```
$ kubectl get cryostat.v1beta1.operator.cryostat.io
W0607 18:14:15.186540  144477 warnings.go:67] use v1beta2 API version
```
> chore(api): deprecate v1beta1 API version

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/certmanager.go
- internal/controllers/reconciler_test.go
- internal/controllers/secrets.go
- internal/test/resources.go
Fixes: #896 
* Detects when updating our CA Issuer causes its secret name to change
* If the secret has changed, delete any certificates owned by the CR (other than the CA), along with the secrets backing those certificates
* The certificates and their secrets will be recreated by the existing reconciliation logic 
* Fixes a bug where Cryostat was serving an old certificate after upgrading from 2.4 to 3.0. This could prevent users from accessing the Cryostat application.
I tested on an OpenShift cluster, since the bug was very apparent when trying to access Cryostat using the route.
1. Build and push an operator controller and bundle image for this PR. (I had to use Docker to make the bundle-upgrade work for some reason.)
* Feel free to use …
> fix(tls): detect modified CA and reissue certs

- README.md
Fixes: #901 
Fixes: #144 
- Added instructions on how to obtain static manifests
Note: `kubectl apply -f` would fail due to annotation size limit. Use `kubectl create -f` instead.
See #901.  A single static manifest that is bundled with all k8s resources allows users to install the operator with `kubectl apply/create -f <manifest-url>`. This aligns with common practice on upstream k8s.
You can follow the instructions in README.
> docs(deploy): add instructions on how to obtain static manifests

- README.md
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
Fixes: https://github.com/cryostatio/cryostatio.github.io/issues/194
Bumped min k8s version in CSV to 1.25.0
See https://github.com/cryostatio/cryostatio.github.io/issues/194#issuecomment-2214103996. Might be a little odd if anyone already installs cryostat-operator with 1.21-1.24 k8s.
> chore(csv): bump csv min k8s version to 1.25

- internal/test/scorecard/common_utils.go
Fixes: #841 
* Avoids overwriting the `cr` variable when calling `Update`. If this fails due to a conflict, the update will be silently retried, but `cr` will now be nil.
* Moves the update and retry to a helper function for convenience
* Fixes a sporadic scorecard test failure encountered downstream
1. `make test-scorecard-local SCORECARD_TEST_SELECTION=cryostat-config-change`
2. In order to reliably reproduce the update conflict, you can use a patch similar to the one listed here: https://github.com/cryostatio/cryostat-operator/issues/841#issuecomment-2221087146
> test(scorecard): preserve CR when retrying on conflict

- .github/workflows/build-ci.yml
Fixes: #914 
- Replaced `podman search` with `curl` to registry v2 api (`quay.io` is compatible). References: https://docker-docs.uclv.cu/registry/spec/api/#existing-manifests
- This sends `HEAD` request to `/v2/<name>/manifests/<reference>` to check if an image exists for the specified tag.
See #914. I avoided fetching tags since the tag list can grow rather large with time. This method should basically query in constant time and also skip pulling the image layers.
Check if a image for specified tag exists:
```bash
TAG=3.0.1-20240704162318
curl -ILs -o /dev/null https://quay.io/v2/cryostat/cryostat-operator-scorecard/manifests/$TAG -w "%{http_code}"
```
Sample run: https://github.com/tthvo/cryostat-operator/actions/runs/9884455121/job/273008 …
> ci(build): query scorecard image tags with registry v2 api

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
Related to https://github.com/cryostatio/cryostat/pull/555
Related to https://github.com/cryostatio/cryostat-helm/pull/159
2. *...*
> chore(rename): update references after repo rename

- bundle/manifests/cryostat-operator-cryostat-namespaced_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/cryostat-operator-manager-config_v1_configmap.yaml
- bundle/manifests/cryostat-operator-oauth-client_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/cryostat-operator-webhook-service_v1_service.yaml
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/default/kustomization.yaml
- config/manifests/kustomization.yaml
Fixes: #924 
* Adds `app.kubernetes.io/name` label to all operator objects using `commonLabels` Kustomize property
* Cleanup: uncomments patch to remove `cert` volume and mount from bundle manifests, which is unneeded when run as a bundle
* Fixes a bug where webhook requests may be sent to other operators in the same namespace
1. Install another operator with a webhook (e.g. Infinispan Operator)
2. Deploy this PR into the same namespace
3. Exercise webhooks by creating and modifying Cryostat CRs
> fix(webhook): make label selectors unambiguous

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
Fixes: #937
See also https://github.com/cryostatio/cryostat-helm/pull/193
Corrects Hibernate-related environment variables for new configuration settings after Flyway was introduced in the main Cryostat container.
1. Check out, build, and deploy PR as usual
2. Open Web UI, go to Recordings, select Target dropdown and click "Create" (to create a custom target)
3. Enter `localhost:0`, click the connection test, then submit the creation request.
4. Before this PR an error notification would appear alongside the target discovery notifications and the custom target creation form would remain visible. After this PR there should be no error notification and the UI should advance to the Topology …
> fix(db): correct hibernate config after Flyway introduction

- Makefile
- internal/controllers/certmanager.go
- internal/controllers/common/common_utils.go
- internal/controllers/common/resource_definitions/certificates.go
- internal/controllers/reconciler.go
- internal/controllers/reconciler_test.go
- internal/controllers/secrets.go
- internal/test/clients.go
- internal/test/resources.go
Fixes: #936 
* Creates a uniquely-named certificate for each target namespace for use by Cryostat agents within it. The certificate has a wildcard hostname within the [namespace subdomain](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records-1), and supports client and server usages.
1. Create a Certificate in the install namespace with a cluster unique name (hashed `install_namespace/cr_name/target_namespace`)
2. Once cert-manager creates the secret in the install namespace, copy it to the target namespace
3. If the target namespace is removed, the Certificate and its secret will be deleted, along with the copy in the target namespace
4. If the CR is deleted, the finalizer allows the operator to delete the …
> feat(tls): generate client certificates for agents

- Makefile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/default/image_pull_patch.yaml
- config/default/image_tag_patch.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_config_patch.yaml
- config/default/manager_webhook_patch.yaml
- config/insights/insights_patch.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/kustomization.yaml
- hack/image_pull_patch.yaml.in
- hack/image_tag_patch.yaml.in
- hack/insights_patch.yaml.in
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/constants/constants.go
- internal/controllers/reconciler_test.go
- internal/test/scorecard/common_utils.go
Fixes: #942 
* Renames the operator's deployment from `cryostat-operator-controller-manager` to `cryostat-operator-controller`
* OLM attempts to patch the deployment during an upgrade. Because we've changed the label selector for the deployment, which is immutable, the upgrade fails. By changing the name of the deployment, OLM will recreate the deployment, instead of patching it, when upgrading the operator.
1. `make deploy_bundle BUNDLE_IMG=quay.io/cryostat/cryostat-operator-bundle:3.0.0`
2. `./bin/operator-sdk run bundle-upgrade quay.io/ebaron/cryostat-operator-bundle:rename-deployment-01`
3. Upgrade should succeed
> fix(olm): rename deployment to handle immutable selector

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
Related to: #942 
#943 included a Scorecard change to lookup the renamed operator deployment, this PR bumps the Scorecard image tag so our CI will build and push a new image.
> chore(scorecard): bump Scorecard image tag

- config/manager/kustomization.yaml
- internal/controllers/certmanager.go
- internal/controllers/common/builder.go
- internal/controllers/common/common_utils.go
- internal/controllers/constants/constants.go
- internal/controllers/cryostat_controller.go
- internal/controllers/rbac.go
- internal/controllers/reconciler.go
- internal/controllers/reconciler_test.go
- internal/main.go
- internal/test/builder.go
- internal/test/reconciler.go
- internal/test/resources.go
Fixes: #941 
* Adds labels to role bindings and secrets created by the operator in target namespaces. These labels identify the name and namespace of the CR responsible for them
* Adds a custom controller watch that filters role bindings and secrets by those labels, and enqueues the identified CR
* Adds a testable wrapper around the controller builder, with a fake implementation for tests.
* Adds tests for each controller watch in the `SetupWithManager` method.
* Allows the operator to watch and respond to deletion of those target namespace objects, or the namespace itself. In the case where the object was deleted, the controller will recreate the deleted object. In the case that the target namespace was deleted, the controller will requeue …
> fix(watch): enqueue CR when target namespace is deleted

- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
See https://github.com/cryostatio/cryostat/pull/690
Enables the `cryostat-storage` flag to turn on SeaweedFS at-rest data encryption.
Improves data security and integrity by ensuring that at-rest files are encrypted. This is not a full solution because Seaweed stores the encryption/decryption key in the file metadata (so that the file can be decrypted later), and in our usage the metadata is stored on the same persistent volume as the encrypted file. So, any attack vectors where the attacker has direct access to the PV bypassing authn/authz checks or the S3 API will still allow the attacker to compromise the data.
1. Build and deploy Operator with this PR
2. Create a Cryostat CR
3. Check the corresponding Cryostat Deployment or Pod …
> feat(storage): enable at-rest encryption on storage container

- Makefile
- README.md
- config/samples/sample-app-agent-tls-proxy.yaml
- config/samples/sample-app-agent.yaml
- config/samples/sample-app.yaml
- **test(sample): update sample application image**
- **test(sample): set up Agent sample application with new image and TLS config**
See https://github.com/cryostatio/test-applications/issues/1
See https://github.com/cryostatio/test-applications/issues/7
Related to https://github.com/cryostatio/cryostat-agent/issues/139
Depends on https://github.com/cryostatio/cryostat-agent/pull/491
Updates the two existing sample app definitions for the newer split TLS truststore/keystore where the Agent's stores are now independent from the host application's stores. Also adds a new sample app definition for an Agent that uses the nginx TLS client auth proxy, rather than the standard OAuth proxy.
1. `make sample_app sample_app_agent …
> test(sample): update sample application images and configs

- README.md
> docs(readme): point user to OperatorHub for installation, move development steps to end

- internal/controllers/services.go
- internal/test/resources.go
Fixes: #<issue number>
See https://github.com/cryostatio/cryostat-helm/pull/211
Related to https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/2
2. *...*
> feat(service): add part-of, instance selector labels and appProtocol

- internal/test/scorecard/clients.go
- internal/test/scorecard/tests.go
See https://github.com/cryostatio/cryostat/pull/698
See #974
Adjusts the test to not expect a full report JSON response body, on request, but only a job ID string response.
Since https://github.com/cryostatio/cryostat/pull/698 the response is expected to be an async job ID on first request, then later the server will emit a websocket notification containing the same ID to notify clients that the request has been completed. Then when the client makes an identical request again, the report is ready and cached, so the server responds with it this second time around.
In the old system the server would always respond with the report response, even though this could sometimes take considerable time to complete. Because of this long delay, with the …
> test(scorecard): adjust scorecard report generation expectation

- internal/webhooks/cryostat_webhook.go
- internal/webhooks/defaulter_test.go
- internal/webhooks/validator.go
- internal/webhooks/validator_test.go
Fixes: #987 
* Adds tests for the Cryostat defaulting webhook
* Reduces visibility of some types if not required to be public
* Increases test coverage
1. `make test-envtest`
> test(webhook): add test for Cryostat defaulter webhook

- Makefile
- config/samples/sample-app-agent.yaml
See https://github.com/cryostatio/cryostat-operator/pull/928
See https://github.com/cryostatio/cryostat-agent/pull/383
Reconfigures the `make sample_app_agent` to use the automatic Kubernetes serviceaccount token detection for authentication/authorization to the auth proxy. This will automatically in OpenShift. In other Kubernetes environments the user will need to patch the resulting Deployment to add `CRYOSTAT_AGENT_AUTHORIZATION` or `CRYOSTAT_AGENT_AUTHORIZATION_TYPE`+`CRYOSTAT_AGENT_AUTHORIZATION_VALUE` environment variables to match any `oauth2-proxy` `Basic` authentication that may be optionally configured.
Exercises the latest best practice of using injected serviceaccount tokens managed by cluster RBAC, rather than using hardcoded …
> test(sampleapp): configure Cryostat Agent sample app to use k8s serviceaccount token auth

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/certmanager.go
- internal/controllers/common/resource_definitions/certificates.go
- internal/controllers/constants/constants.go
- internal/controllers/reconciler_test.go
- internal/test/resources.go
> fix(tls): use fixed-length cert CommonNames

- Dockerfile
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/tests/scorecard/config.yaml
- config/scorecard/patches/custom.config.yaml
- internal/images/custom-scorecard-tests/Dockerfile
Fixes: #<issue number>
2. *...*
> build(oci): switch builder image to ubi9 go toolset

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/default/kustomization.yaml
- config/default/webhook_object_selector_patch.yaml
- internal/webhooks/agent/pod_defaulter.go
Fixes: #993 
* Patches the MutatingWebhookConfiguration with an object selector that causes the pod webhook to only be invoked if it contains the required `cryostat.io/name` and `cryostat.io/namespace` labels
* Increases performance by using Kubernetes to perform server-side filtering so our webhook isn't invoked upon every pod creation event in the cluster
1. Deploy PR and create a default CR
2. `make sample_app`, there should be no log messages from `pod-webhook`. If the filtering didn't work, we would see the new "pod is missing required labels" log message.
3. `make sample_app_agent_injected`. You should see a `pod-webhook` log message like "configured Cryostat agent for pod" and the sample app should be properly instrumented
> feat(agent): add object selector for pod webhook

- config/samples/sample-app-agent-injected.yaml
- internal/controllers/constants/constants.go
- internal/webhooks/agent/pod_defaulter.go
- internal/webhooks/agent/pod_defaulter_test.go
- internal/webhooks/agent/test/resources.go
Fixes: #994 
* Adds a `cryostat.io/container` label. If present on an auto-configured pod, the mutation webhook will look for the named container instead of defaulting to the first container.
* Removes RBAC and agent-related port from injected sample app. We want to make sure if works with default RBAC and no prior setup.
* Allows agent auto-configuration to work in multi-container pods
1. Deploy PR and create default CR
2. Create a modified sample app with an extra container such as:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app: quarkus-cryostat-agent
name: quarkus-cryostat-agent
spec:
replicas: 1
selector:
matchLabels:
app: quarkus-cryostat-agent
template:
metadata:
labels:
app: quarkus-cryostat-agent …
```
> feat(agent): add label to control which container is mutated

- .github/workflows/build-ci.yml
- .github/workflows/test-ci-push.yml
Related to #687
Related to #1023
Sample runs:
`k8s`: https://github.com/andrewazores/cryostat-operator/actions/runs/12991924912/job/36230608257
```
Run redhat-actions/push-to-registry@v2
Creating temporary Podman image storage for pulling from Docker daemon
Storage driver is not 'overlay', so not overriding storage configuration
Combining image name "cryostat-operator-bundle" and registry "quay.io/andrewazores" to form registry path "quay.io/andrewazores/cryostat-operator-bundle"
🔍 Checking if the given image is manifest or not.
/usr/bin/podman version
/usr/bin/podman manifest exists cryostat-operator-bundle:4.0.0-dev-k8s
/usr/bin/podman manifest exists cryostat-operator-bundle:4.0.0-dev
/usr/bin/podman manifest exists …
```
> ci(bundle): build plain-k8s and OCP bundle modes

- internal/controllers/constants/constants.go
- internal/webhooks/agent/pod_defaulter.go
- internal/webhooks/agent/pod_defaulter_test.go
- internal/webhooks/agent/test/resources.go
Fixes: #996 
* Adds `cryostat.io/read-only` label to allow users to make the injected agent read-only. 
* Gives users more control over security of their injected agents
1. Deploy this PR and create default CR
2. `make sample_app_injected`, should inject with write access turned on
3. Edit deployment with `cryostat.io/read-only: true`, should inject with write access turned off
> feat(agent): add label for read-only agent

- internal/console/console_suite_test.go
- internal/console/plugin.go
- internal/console/plugin_test.go
- internal/console/test/resources.go
- internal/controllers/constants/constants.go
Fixes: #1030 
* Use the ClusterVersion API to find the cluster's OpenShift version
* Log a message instead of installing the ConsolePlugin and modifying the Console CR
* This prevents installing a broken plugin on older versions of OpenShift
1. Generate a bundle image from this PR `make bundle BUNDLE_MODE=ocp ...`
2. Try it on an OpenShift >= 4.15 cluster, it should install the plugin and it should function
3. Try it on an OpenShift < 4.15 cluster, it should not install the plugin and instead log a message:
`OpenShift version 4.12.0 is older than the minimum required (4.15.0) for the Console Plugin. Plugin installation will be skipped.`
> fix(plugin): check OpenShift version compatibility

- internal/controllers/constants/constants.go
- internal/controllers/services.go
- internal/test/resources.go
Fixes: #1033
Related to cryostatio/cryostat-openshift-console-plugin#3
Sets the `appProtocol` of the Cryostat service port to `https` if TLS is enabled, otherwise leaves it as `http`.
This is used as a marker for other components to know whether the exposed service port is using HTTPS or HTTP. The console plugin backend uses the appProtocol first to determine whether it should send HTTPS or HTTP requests to the Cryostat instance. If it does not find an appProtocol on the port then it falls back to trying to use the port name. If it still cannot determine what the port is, then it bails out.
2. *...*
> fix(service): set appProtocol to https if TLS enabled

- internal/controllers/constants/constants.go
- internal/webhooks/agent/pod_defaulter.go
- internal/webhooks/agent/pod_defaulter_test.go
- internal/webhooks/agent/test/resources.go
Fixes: #1001 
* Adds a `cryostat.io/java-options-var` label whose value is used instead of `JAVA_TOOL_OPTIONS` to inject the Cryostat agent
* Allows more flexibility to users where `JAVA_TOOL_OPTIONS` may not work for their application
1. Deploy PR and create default CR
2. `kubectl create deploy wildfly --image=quay.io/wildfly/wildfly:latest-jdk17 --port=8080`
3. Edit the wildfly pod template to add the following labels:
```yaml
cryostat.io/name: cryostat-sample
cryostat.io/namespace: cryostat-operator-system
cryostat.io/java-options-var: MODULE_OPTS
```
4. The wildfly pod is created with `MODULE_OPTS` used to inject the agent
5. The agent should run and register properly with Cryostat
> feat(agent): add label for Java options variable name

- bundle/manifests/cryostat-operator-cryostat_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/rbac/cryostat_role.yaml
- config/rbac/role.yaml
- internal/controllers/cryostat_controller.go
Related to: #951 
* Removes `oauthaccesstokens` and `selfsubjectaccessreviews` from the operator's cluster role and also from the cluster role bound to Cryostat service accounts. 
* These permissions were needed before we migrated to using the OpenShift OAuth Proxy sidecar. It's good security practice to remove unneeded permissions.
1. Deploy PR
2. Inspect the `cryostat-operator-cryostat` ClusterRole and verify the permissions are removed.
> fix(rbac): remove unused permissions from ClusterRole

- internal/controllers/configmaps.go
- internal/controllers/reconciler_test.go
- internal/test/resources.go
Fixes: #984 
* Removes `Immutable` property from OAuth2 Proxy config map
* Deletes and recreates existing config maps with `Immutable: true`
* Adds test cases for the config map
* Fixes an issue where `passHostHeader` and `proxyWebSockets` were not in the generated JSON
* Allows users to disable cert-manager on an existing Cryostat instance
1. On Kubernetes, `make deploy_bundle BUNDLE_IMG=quay.io/cryostat/cryostat-operator-bundle:3.0.1`
2. `make create_cryostat_cr`
3. Build a bundle image for this PR
4. ./bin/operator-sdk run bundle-upgrade --timeout 5m <bundle image for this PR>
5. Check that `Immutable` property is no longer present in config map
6. Edit CR to disable cert-manager, it should redeploy Cryostat properly
> fix(oauth): make OAuth2 Proxy config map mutable

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- config/default/image_tag_patch.yaml
- hack/image_tag_patch.yaml.in
Fixes: #970
Depends on: #1041
* This was a piece missed in #991 that adds the configurable agent init image to the list of related images in the CSV.
* Needed for [disconnected](https://docs.openshift.com/container-platform/4.17/operators/operator_sdk/osdk-generating-csvs.html#olm-enabling-operator-for-restricted-network_osdk-generating-csvs) installation of the operator
1. Build/deploy
2. CSV should have the expected relatedImages entry and corresponding environment variable in the deployment
> build(agent): add agent init image to related images

- Makefile
- config/insights/insights_image_pull_patch.yaml
- config/insights/kustomization.yaml
- hack/insights_image_pull_patch.yaml.in
Fixes: #691 
* Adds a Kustomize patch to control pull policy in the same way we do for the operator controller and console plugin
* Makes pull policy consistent across images
1. `make bundle`
> build(insights): add Kustomize patch to adjust pull policy

- internal/test/scorecard/common_utils.go
Fixes: https://github.com/cryostatio/cryostat-operator/issues/1059
2. *...*
> test(scorecard): disable NetworkPolicies during scorecard testing

- config/overlays/insights/insights_manager_patch.yaml
- config/overlays/insights/insights_patch.yaml
- config/overlays/insights/kustomization.yaml
- hack/insights_patch.yaml.in
Fixes: #1072 
* Adds a new JSON patch to append the Insights variables to the end of the environment variable array
* Allows the optional Insights integration to work again
1. `make bundle ENABLE_INSIGHTS=true`
2. Verify that the `OPERATOR_NAMESPACE` variable is defined before `INSIGHTS_URL`
> fix(insights): correct environment variable order in overlay

- api/v1beta2/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/reconciler_test.go
- internal/test/resources.go
See #1011
Adds a simple toggle to set `cryostat.agent.tls.required=false`.
For manual (non-autoconfig) Agent setups, in testing or prototyping scenarios, it can be difficult or complicated to set up TLS fully. This toggle can be used to allow insecure HTTP Agent callback URLs again, since 4.0 enforces this requirement by default whereas prior Cryostat versions did not. This would also be required for agent autoconfiguration to work if cert-manager integration is disabled, though I haven't specifically tested that scenario yet and more might need to be done.
2. *...*
> feat(agent): add toggle to allow insecure connections

- internal/webhooks/agent/pod_defaulter.go
- internal/webhooks/agent/test/resources.go
Related to: #1076
* Sets `CRYOSTAT_AGENT_WEBCLIENT_TLS_REQUIRED` to false when cert-manager is disabled
* Allows users to connect agents to Cryostat instances where cert-manager integration is disabled
> fix(agent): don't require TLS when cert-manager is disabled

- internal/webhooks/agent/pod_defaulter_test.go
Related to: #1081 
* Test image pull policy only for stubbed image tags
* Fixes the test failure when running on a release tag
1. `make test-envtest`
> test(agent): fix failing pull policy test on release

- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/test/resources.go
Fixes: #1100
Corrects the configuration key (environment variable name) that the Operator sets to inform Cryostat about the URL for the report generator sidecar service.
The key currently used is outdated and no longer used, so Cryostat ignores it and handles report generation on its own rather than shifting it onto the report generator instance(s). This means that report generator configuration is currently useless.
1. Check out and build PR
2. Deploy Operator, create Cryostat CR with `reportOptions: { replicas: 1 }`
3. `make sample_app` in a target namespace
4. Wait for everything to come up, then open the Cryostat UI and request a target analysis on the sample app, or request analysis of an archived recording.
5. Check the reports Pod …
> fix(reports): correct reports service URL configuration key

- internal/test/scorecard/common_utils.go
- internal/test/scorecard/tests.go
Follow-up: #814 
As of v4.0 (i.e. after #814), the main deployment is split into main, database and storage. Thus, scorecard test needs to adapt to wait for the database and storage deployment availability before proceeding further in tests.
The fix is included in commit: https://github.com/cryostatio/cryostat-operator/commit/0cf7dba526b5168e9d6a64c9818a5d6357e6ef5b. I added some clean-up a separate one.
See https://github.com/cryostatio/cryostat-operator/pull/1101#issuecomment-2839479502
> test(scorecard): verify database and storage deployment availability

- Makefile
- config/samples/sample-app-agent-injected.yaml
- config/samples/sample-app.yaml
Related to https://github.com/cryostatio/cryostat-agent/issues/634
Adds liveness and readiness probes to two of the sample app definitions. These are the two that represent the common cases - an Agent-less application that is discovered by Endpoints (EndpointSlice) and uses JMX, and an autoconfig-injected Agent.
Make these two sample app cases more representative of real production workloads which should be expected to use liveness and readiness probes.
1. Deploy Operator, create CR, etc. as usual
2. `make sample_app` and `make sample_app_agent_injected` as usual, ensuring that discovery for both works as usual and that Kubernetes reports both as alive and ready to accept traffic. Check the injected Agent's logs in the application Pod and …
> test(samples): add liveness/readiness probes to sample apps

- api/v1beta2/cryostat_types.go
- bundle/manifests/cryostat-operator.clusterserviceversion.yaml
- bundle/manifests/operator.cryostat.io_cryostats.yaml
- config/crd/bases/operator.cryostat.io_cryostats.yaml
- config/manifests/bases/cryostat-operator.clusterserviceversion.yaml
- docs/config.md
- internal/controllers/common/common_utils.go
- internal/controllers/common/resource_definitions/resource_definitions.go
- internal/controllers/reconciler_test.go
- internal/test/resources.go
- internal/webhooks/agent/pod_defaulter.go
- internal/webhooks/agent/pod_defaulter_test.go
- internal/webhooks/agent/test/resources.go
Fixes: #1155 
* Adds default resource limits (2-3x default requests) for each container managed by the operator
* Default resource limits won't be set if the user supplies either a resource request or limit for that container in the CR
* Updates the docs to reflect this change
* This prevents Cryostat from consuming excess resources and negatively affecting other workloads
1. Deploy and create default CR, observe new default limits
2. Customize CR and see changes applied
> feat(deploy): apply default resource limits
